### ISSUE TITLE
Entities crash

### ISSUE THREAD

**Issue by NapoElWapo** [deepnight/ldtk#1001]
Whenever i enter the entities tab or a entity layer the program crashes:

Here is the error that LDTK shows. 
Stack:
```
LDtk version: 1.4.1-64bits
Cannot read properties of null (reading 'createTileHtmlImageFromRect')
TypeError
TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.updateTool (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208787:8)
    at page_Editor.onGlobalEvent (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:217573:9)
    at misc_GlobalEventDispatcher.emit (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203255:4)
    at page_Editor.selectLayerInstance (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:214348:11)
    at ui_modal_panel_EditLayerDefs.updateForm (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:271135:18)
```
Processes:
```
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.IntGridTool [PAUSED][--]
       |--- #103 ui.Notification
       |--- #108 ui.modal.panel.EditLayerDefs
       |--- #109 display.EntityRender
       |--- #110 display.EntityRender
       |--- #111 display.EntityRender
       |--- #112 display.EntityRender
       |--- #113 display.EntityRender
       |--- #114 display.EntityRender
       |--- #115 display.EntityRender
       |--- #117 tool.lt.EntityTool[--]
```

Log:
```
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[SAVE]         Preparing project saving: C:/Users/Cuajo/Documents/Universidad/Semestre9/disenio/MT/missile-toad/build/bin/assets/levels/testRoom.ldtk...
[SAVE]         => PreChecks...
[SAVE]         => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         => AutoLayers...
[GENERAL]      Progress created.
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "Preparing levels...", 3 operation(s)
[GENERAL]      Progress completed: "Preparing levels..." (0s)
[SAVE]         => SavingMainFile...
[GENERAL]      Progress created.
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "Saving main file...", 2 operation(s)
[SAVE]           Preparing SavingData...
[SAVE]           Writing C:/Users/Cuajo/Documents/Universidad/Semestre9/disenio/MT/missile-toad/build/bin/assets/levels/testRoom.ldtk...
[GENERAL]      Progress completed: "Saving main file..." (0s)
[FILE]         Emptying dir C:/Users/Cuajo/Documents/Universidad/Semestre9/disenio/MT/missile-toad/build/bin/assets/levels/testRoom (onlyExts=[ldtkl])...
[SAVE]         => Done...
[SAVE]         Saving complete (testRoom.ldtk)
[FILE]         Saved "testRoom.ldtk".
[EVENT]        ProjectSaved
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level fields data.Level#c57f3570-6280-11ee-b4ce-99aea659bc81 "Level_0"...
[RENDER]       Rendering world level fields data.Level#c4ce99f0-6280-11ee-a754-7b86726422c1 "Level_1"...
[RENDER]       Rendering world level fields data.Level#931ff490-6280-11ee-a754-3d64f1cf7f58 "Level_2"...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #108 ui.modal.panel.EditLayerDefs
[USERACTION]   Closed panel #84 ui.modal.panel.WorldPanel
[FILE]         Loading HTML template editLayerDefs
[RENDER]       Rendering world level fields data.Level#c4ce99f0-6280-11ee-a754-7b86726422c1 "Level_1"...
[WARNING]      Full level render requested
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceSelected
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'createTileHtmlImageFromRect') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.updateTool (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208787:8)
    at page_Editor.onGlobalEvent (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:217573:9)
    at misc_GlobalEventDispatcher.emit (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203255:4)
    at page_Editor.selectLayerInstance (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:214348:11)
    at ui_modal_panel_EditLayerDefs.updateForm (file:///C:/Users/Cuajo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:271135:18)

[GENERAL]      
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.IntGridTool [PAUSED][--]
       |--- #103 ui.Notification
       |--- #108 ui.modal.panel.EditLayerDefs
       |--- #109 display.EntityRender
       |--- #110 display.EntityRender
       |--- #111 display.EntityRender
       |--- #112 display.EntityRender
       |--- #113 display.EntityRender
       |--- #114 display.EntityRender
       |--- #115 display.EntityRender
       |--- #117 tool.lt.EntityTool[--]
 |--- #118 page.CrashReport

[FILE]         Cleared all file watches
```

[testRoom.zip](https://github.com/deepnight/ldtk/files/13452884/testRoom.zip)

**Comment by NapoElWapo** [comment]
I saw that this is the same issue as #999
