### ISSUE TITLE
Crash when adding attempting entity to a level 

### ISSUE THREAD

**Issue by gummycookie** [deepnight/ldtk#1050]
The project I am is just a playground project to test an importer. 

* Added 2 levels
* Created an Entities layer
* Created an Entity
* Attempted to place the entity on a level

Stack:
```
LDtk version: 1.5.2-64bits
Cannot read properties of undefined (reading 'maxCount')
TypeError
TypeError: Cannot read properties of undefined (reading 'maxCount')
    at tool_lt_EntityTool.startUsing (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:265359:112)
    at page_Editor.onMouseDown (file://AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:238169:25)
    at page_Editor.onHeapsEvent (file:///AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:238080:9)
    at h2d_Scene.dispatchListeners (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:142756:4)
    at hxd_SceneEvents.dispatchListeners (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:189933:6)
    at hxd_SceneEvents.emitEvent (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:189763:9)
    at hxd_SceneEvents.checkEvents (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:189849:10)
    at Boot.mainLoop (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5148:16)
    at hxd_System.browserLoop (file:///AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:190608:14)
```
Processes:
```
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #277 tool.lt.EntityTool[Add] [RUNNING]
       |--- #301 tool.lt.IntGridTool [PAUSED][--]
```

Log:
```
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Closed panel #271 ui.modal.panel.EditLayerDefs
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #288 ui.modal.panel.EditEntityDefs
[FILE]         Loading HTML template editEntityDefs
[FILE]         Loading HTML template fieldDefsForm
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template pivotEditor from cache
[EVENT]        EntityDefAdded
[FILE]         Reading HTML template pivotEditor from cache
[RENDER]       Rendering world bg...
[EVENT]        EntityDefChanged
[FILE]         Reading HTML template pivotEditor from cache
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template colorPicker from cache
[RENDER]       Rendering world bg...
[EVENT]        EntityDefChanged
[FILE]         Reading HTML template pivotEditor from cache
[FILE]         Reading HTML template pivotEditor from cache
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Closed panel #288 ui.modal.panel.EditEntityDefs
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceSelected 3
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceSelected 26
[RENDER]       Rendered level UI
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Claire Li/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of undefined (reading 'maxCount') (TypeError)
[ERROR]        TypeError: Cannot read properties of undefined (reading 'maxCount')
    at tool_lt_EntityTool.startUsing (file:///C://AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:265359:112)
    at page_Editor.onMouseDown (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:238169:25)
    at page_Editor.onHeapsEvent (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:238080:9)
    at h2d_Scene.dispatchListeners (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:142756:4)
    at hxd_SceneEvents.dispatchListeners (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:189933:6)
    at hxd_SceneEvents.emitEvent (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:189763:9)
    at hxd_SceneEvents.checkEvents (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:189849:10)
    at Boot.mainLoop (file:////AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5148:16)
    at hxd_System.browserLoop (file:///i/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:190608:14)

[GENERAL]      
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #277 tool.lt.EntityTool[Add] [RUNNING]
       |--- #301 tool.lt.IntGridTool [PAUSED][--]
 |--- #302 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Fixed
