### ISSUE TITLE
File in an "unsavable state", I closed Godot (which read the files), didnt fix

### ISSUE THREAD

**Issue by sevansevan** [deepnight/ldtk#1062]
Stack:
```
LDtk version: 1.5.3-64bits
EBUSY: resource busy or locked, rmdir '\\?\S:\Derelict\project\scenes\ldtk_export\ldtk_levels\simplified\Level_2'
Error
Error: EBUSY: resource busy or locked, rmdir '\\?\S:\Derelict\project\scenes\ldtk_export\ldtk_levels\simplified\Level_2'
    at rmdirSync (node:fs:1226:10)
    at _rmdirSync (node:internal/fs/rimraf:235:5)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmdirSync (node:fs:1218:14)
    at dn_js_NodeTools.removeDir (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:120401:13)
    at ui_ProjectSaver.beginState (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:286826:23)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.TileTool[--]
       |--- #66 tool.lt.EntityTool [PAUSED][--]
       |--- #412 display.EntityRender
       |--- #413 display.EntityRender
       |--- #414 display.EntityRender
       |--- #415 display.EntityRender
       |--- #416 display.EntityRender
       |--- #417 display.EntityRender
       |--- #418 ui.ProjectSaver
       |--- #419 ui.modal.MetaProgress
       |--- #422 ui.modal.Progress
```

Log:
```
[RENDER]       Rendering world level data.Level#0c2868e0-b0a0-11ee-a389-bf63323e9867 "Level_0"...
[RENDER]       Rendering world level fields data.Level#0c2868e0-b0a0-11ee-a389-bf63323e9867 "Level_0"...
[RENDER]       Rendering world level data.Level#cef06dc0-b0a0-11ee-b11a-8d1406d2db0f "Level_1"...
[EVENT]        LayerInstanceEditedByTool
[USERACTION]   TileTool: mode=Add, in LayerInst#9 "Tiles" [Tiles]
[SAVE]         Preparing project saving: S:\Derelict\project\scenes\ldtk_export\ldtk_levels.ldtk...
[CACHE]        Garbaging unused image LdtkIcons_272_32_16_16...
[CACHE]        Disposing cached image LdtkIcons_272_32_16_16...
[CACHE]        Garbaging unused image LdtkIcons_272_0_16_16...
[CACHE]        Disposing cached image LdtkIcons_272_0_16_16...
[CACHE]        Garbaging unused image LdtkIcons_320_320_16_32...
[CACHE]        Disposing cached image LdtkIcons_320_320_16_32...
[CACHE]        Garbaging unused image LdtkIcons_0_736_16_32...
[CACHE]        Disposing cached image LdtkIcons_0_736_16_32...
[CACHE]        Garbaging unused image LdtkIcons_288_608_32_64...
[CACHE]        Disposing cached image LdtkIcons_288_608_32_64...
[CACHE]        Garbaging unused image LdtkIcons_0_240_16_16...
[CACHE]        Disposing cached image LdtkIcons_0_240_16_16...
[CACHE]        Garbaging unused image LdtkIcons_16_240_16_16...
[CACHE]        Disposing cached image LdtkIcons_16_240_16_16...
[SAVE]         => PreChecks...
[SAVE]         => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         => AutoLayers...
[GENERAL]      Progress created.
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "Preparing levels...", 4 operation(s)
[GENERAL]      Progress completed: "Preparing levels..." (0s)
[SAVE]         => SavingMainFile...
[GENERAL]      Progress created.
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "Saving main file...", 2 operation(s)
[SAVE]           Preparing SavingData...
[SAVE]           Writing S:\Derelict\project\scenes\ldtk_export\ldtk_levels.ldtk...
[GENERAL]      Progress completed: "Saving main file..." (0s)
[SAVE]         => SavingExternLevels...
[FILE]         Emptying dir S:\Derelict\project\scenes\ldtk_export\ldtk_levels (onlyExts=[ldtkl])...
[GENERAL]      Progress created.
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "Saving levels", 4 operation(s)
[GENERAL]      Progress completed: "Saving levels" (0s)
[SAVE]         => WritingImages...
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        EBUSY: resource busy or locked, rmdir '\\?\S:\Derelict\project\scenes\ldtk_export\ldtk_levels\simplified\Level_2' (Error)
[ERROR]        Error: EBUSY: resource busy or locked, rmdir '\\?\S:\Derelict\project\scenes\ldtk_export\ldtk_levels\simplified\Level_2'
    at rmdirSync (node:fs:1226:10)
    at _rmdirSync (node:internal/fs/rimraf:235:5)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at node:internal/fs/rimraf:253:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (node:internal/fs/rimraf:250:7)
    at rimrafSync (node:internal/fs/rimraf:193:7)
    at Object.rmdirSync (node:fs:1218:14)
    at dn_js_NodeTools.removeDir (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:120401:13)
    at ui_ProjectSaver.beginState (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:286826:23)

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.TileTool[--]
       |--- #66 tool.lt.EntityTool [PAUSED][--]
       |--- #412 display.EntityRender
       |--- #413 display.EntityRender
       |--- #414 display.EntityRender
       |--- #415 display.EntityRender
       |--- #416 display.EntityRender
       |--- #417 display.EntityRender
       |--- #418 ui.ProjectSaver
       |--- #419 ui.modal.MetaProgress
       |--- #422 ui.modal.Progress
 |--- #423 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by sevansevan** [comment]
Turns out visual studio code the data.json opened.
Closing it fixed it.
