### ISSUE TITLE
Cannot read properties of null (reading 'externalLevels'

### ISSUE THREAD

**Issue by PainOfExistance** [deepnight/ldtk#1074]
Stack:
```
LDtk version: 1.5.3-64bits
Cannot read properties of null (reading 'externalLevels')
TypeError
TypeError: Cannot read properties of null (reading 'externalLevels')
    at Object.cb (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:285488:8)
    at ui_modal_Progress.update (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:292554:8)
    at dn_Process._doMainUpdate (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:405:4)
    at dn_Process.updateAll (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:675:14)
    at Boot.update (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5190:14)
    at Boot.mainLoop (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5152:8)
    at hxd_System.browserLoop (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:190796:14)
```
Processes:
```
#0 App
 |--- #1 page.Home
 |--- #3 page.Home
 |--- #5 page.Home
#2 ui.modal.Progress
#4 ui.modal.dialog.LogPrint
#6 ui.modal.dialog.LogPrint
```

Log:
```


[BOOT]         App started
[BOOT]         Version: 1.5.3-64bits (build 473703)
[BOOT]         ExePath: C:/Users/MatejPC/AppData/Local/Programs/ldtk
[BOOT]         Assets: C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets
[BOOT]         ExtraFiles: C:/Users/MatejPC/AppData/Local/Programs/ldtk/extraFiles
[BOOT]         CWD: C:\Users\MatejPC\AppData\Local\Programs\ldtk\
[BOOT]         Display: 2560x1440
[BOOT]         Args: soloValues=[], args=[]
[FILE]         Loading settings from C:/Users/MatejPC/AppData/Roaming/LDtk/settings...
[BOOT]         AppZoomFactor: 1
[BOOT]         Calling appReady...
[UPDATE]       Looking for update
[BOOT]         Start args: path=null levelIndex=null
[BOOT]         Loading Home...
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/home.html
[DEBUG]        samplesDir=C:/Users/MatejPC/AppData/Local/Programs/ldtk/extraFiles/samples
[GENERAL]      Progress created.
[GENERAL]      Progress started: : "worlds.ldtk: Project...", 5 operation(s)
[LOAD]         Loading project worlds.ldtk...
[ERROR]        SyntaxError: Expected ',' or ']' after array element in JSON at position 2621440
[ERROR]        Failed to load project: D:\FindingHabo\terrain\worlds.ldtk levelIdx=undefined
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/home.html
[DEBUG]        samplesDir=C:/Users/MatejPC/AppData/Local/Programs/ldtk/extraFiles/samples
[FILE]         Loading HTML template logPrint
[ERROR]        TypeError: Cannot read properties of null (reading 'iid')
[ERROR]        Failed to load project: D:\FindingHabo\terrain\worlds.ldtk levelIdx=undefined
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/home.html
[DEBUG]        samplesDir=C:/Users/MatejPC/AppData/Local/Programs/ldtk/extraFiles/samples
[FILE]         Reading HTML template logPrint from cache
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'externalLevels') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'externalLevels')
    at Object.cb (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:285488:8)
    at ui_modal_Progress.update (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:292554:8)
    at dn_Process._doMainUpdate (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:405:4)
    at dn_Process.updateAll (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:675:14)
    at Boot.update (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5190:14)
    at Boot.mainLoop (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5152:8)
    at hxd_System.browserLoop (file:///C:/Users/MatejPC/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:190796:14)

[GENERAL]      
#0 App
 |--- #1 page.Home
 |--- #3 page.Home
 |--- #5 page.Home
 |--- #7 page.CrashReport
#2 ui.modal.Progress
#4 ui.modal.dialog.LogPrint
#6 ui.modal.dialog.LogPrint

```

**Comment by deepnight** [comment]
Thanks for reporting! Did this happen in a specific context?

**Comment by PainOfExistance** [comment]
> Thanks for reporting! Did this happen in a specific context?

Sorry for late response, nope i just opened worlds.ldtk file that I've been using to work on and this popped up and now i can edit my world.

**Comment by OvercookedBeef** [comment]
I just opened LDtk for the first time (installed from the AUR package `ldtk-bin`) and I'm getting this error every time I open the software.
