### ISSUE TITLE
Crashing on trying to delete enum

### ISSUE THREAD

**Issue by Kryptoid987** [deepnight/ldtk#1118]
Stack:
```
LDtk version: 1.5.3-64bits
Cannot read properties of undefined (reading 'externalRelPath')
TypeError
TypeError: Cannot read properties of undefined (reading 'externalRelPath')
    at data_def_FieldDef.getJsonTypeString (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:40563:15)
    at data_inst_FieldInstance.toJson (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:47847:58)
    at data_Level.toJson (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:33693:44)
    at LevelTimeline.saveFullLevelState (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:16840:126)
    at LevelTimeline.clear (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:16565:9)
    at LevelTimeline.manualOnGlobalEvent (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:16677:9)
    at page_Editor.onGlobalEvent (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:246817:8)
    at misc_GlobalEventDispatcher.emit (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:229296:4)
    at _delete (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:304280:23)
    at ui_modal_panel_EditEnumDefs.deleteEnumDef (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:304325:5)
```
Processes:
```
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.TileTool[--]
       |--- #28 ui.modal.panel.EditEnumDefs
       |--- #30 ui.modal.ContextMenu
       |--- #33 ui.Tip
       |--- #34 ui.LastChance
```

Log:
```
[FILE]         Watching file: D:/Playdate/PlatformerPrototype/source/levels/tileset-table-24-24.png
[RENDER]       Rendering world level data.Level#abbda0b0-25d0-11ef-9c9d-ad16732125be "WoodmanNES_0"...
[RENDER]       Rendering world level fields data.Level#abbda0b0-25d0-11ef-9c9d-ad16732125be "WoodmanNES_0"...
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[GENERAL]      Progress completed: "MegamanTest.ldtk: Project..." (0.3s)
[RENDER]       Rendering world level data.Level#97545110-25d0-11ef-9144-ed4ec917c7a0 "WoodmanNES_2"...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #19 ui.modal.panel.LevelInstancePanel
[FILE]         Loading HTML template levelInstancePanel
[FILE]         Loading HTML template levelInstanceForm
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #22 ui.modal.panel.EditLayerDefs
[USERACTION]   Closed panel #19 ui.modal.panel.LevelInstancePanel
[FILE]         Loading HTML template editLayerDefs
[FILE]         Loading HTML template pivotEditor
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #28 ui.modal.panel.EditEnumDefs
[USERACTION]   Closed panel #22 ui.modal.panel.EditLayerDefs
[FILE]         Loading HTML template editEnumDefs
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[WARNING]      Last chance for: Enum Df deleted
[EVENT]        EnumDefRemoved
[EVENT]        LevelJsonCacheInvalidated
[EVENT]        LevelJsonCacheInvalidated
[EVENT]        LevelJsonCacheInvalidated
[EVENT]        LevelJsonCacheInvalidated
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of undefined (reading 'externalRelPath') (TypeError)
[ERROR]        TypeError: Cannot read properties of undefined (reading 'externalRelPath')
    at data_def_FieldDef.getJsonTypeString (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:40563:15)
    at data_inst_FieldInstance.toJson (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:47847:58)
    at data_Level.toJson (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:33693:44)
    at LevelTimeline.saveFullLevelState (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:16840:126)
    at LevelTimeline.clear (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:16565:9)
    at LevelTimeline.manualOnGlobalEvent (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:16677:9)
    at page_Editor.onGlobalEvent (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:246817:8)
    at misc_GlobalEventDispatcher.emit (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:229296:4)
    at _delete (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:304280:23)
    at ui_modal_panel_EditEnumDefs.deleteEnumDef (file:///C:/Users/krypt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:304325:5)

[GENERAL]      
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.TileTool[--]
       |--- #28 ui.modal.panel.EditEnumDefs
       |--- #30 ui.modal.ContextMenu
       |--- #33 ui.Tip
       |--- #34 ui.LastChance
 |--- #35 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by Kryptoid987** [comment]
I managed to delete the enum once I realized I had levels custom data accessing it
