### ISSUE TITLE
LDtk crash working with int grid

### ISSUE THREAD

**Issue by Madour** [deepnight/ldtk#209]
The crash happens when I delete a selected grid value.

Let's say I have an IntGrid layer with 2 grid values "0 black" and  "1 red". If I remove the "1 red" grid value while it is selected as active value, the program will crash directly or after I close the Layer panel.

`Cannot read property 'color' of undefined (TypeError)`

Clicking on the X over the red grid value will make the program crash

![image](https://user-images.githubusercontent.com/11854124/98709248-6c9ed000-2382-11eb-93cf-8618c707340f.png)
 

Stack:
```
LDtk version: 0.5.2-beta
Cannot read property 'color' of undefined
TypeError
TypeError: Cannot read property 'color' of undefined
    at tool_lt_IntGridTool.updateCursor (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:84779:74)
    at tool_lt_IntGridTool.onMouseMove (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:8719:11)
    at tool_lt_IntGridTool.onMouseMove (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:84786:40)
    at page_Editor.onMouseMove (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:78084:24)
    at page_Editor.onHeapsEvent (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:78019:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:36572:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:56018:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:55865:9)
    at hxd_SceneEvents.checkEvents (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:55951:10)
    at Boot.mainLoop (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1334:16)
```
Processes:
```
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 ui.Cursor
       |--- #5 display.LevelRender
       |--- #6 display.Rulers
       |--- tool.SelectionTool[--]
       |--- tool.lt.DoNothing[--]
       |--- #9 Option watcher (singleLayerMode)
       |--- #10 Option watcher (grid)
       |--- #11 Option watcher (emptySpaceSelection)
       |--- #12 Option watcher (tileStacking)
       |--- #22 ui.modal.panel.EditLayerDefs
       |--- tool.lt.IntGridTool[--]
```

Log:
```

[BOOT]         App started
[BOOT]         Args: soloValues=[], args=[]
[FILE]         Loading settings...
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/home.html
[NETWORK]      Looking for update
[GENERAL]      Page started: page.Editor()
[FILE]         Loading page template: editor from C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/editor.html
[FILE]         Cleared all file watches
[EVENT]        LayerInstanceSelected
[EVENT]        LayerDefChanged
[WARNING]      Full render requested
[EVENT]        LayerDefChanged
[WARNING]      Full render requested
[EVENT]        LayerDefChanged
[WARNING]      Full render requested
[FILE]         Reading HTML template editLayerDefs from cache
[EVENT]        LayerDefChanged
[WARNING]      Full render requested
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'color' of undefined (TypeError)
[ERROR]        TypeError: Cannot read property 'color' of undefined
    at tool_lt_IntGridTool.updateCursor (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:84779:74)
    at tool_lt_IntGridTool.onMouseMove (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:8719:11)
    at tool_lt_IntGridTool.onMouseMove (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:84786:40)
    at page_Editor.onMouseMove (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:78084:24)
    at page_Editor.onHeapsEvent (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:78019:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:36572:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:56018:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:55865:9)
    at hxd_SceneEvents.checkEvents (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:55951:10)
    at Boot.mainLoop (file:///C:/Users/Abdar2/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1334:16))

[GENERAL]      
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 ui.Cursor
       |--- #5 display.LevelRender
       |--- #6 display.Rulers
       |--- tool.SelectionTool[--]
       |--- tool.lt.DoNothing[--]
       |--- #9 Option watcher (singleLayerMode)
       |--- #10 Option watcher (grid)
       |--- #11 Option watcher (emptySpaceSelection)
       |--- #12 Option watcher (tileStacking)
       |--- #22 ui.modal.panel.EditLayerDefs
       |--- tool.lt.IntGridTool[--]
 |--- #25 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by Madour** [comment]
I looked a bit into the code following the stack trace,
https://github.com/deepnight/ldtk/blob/2590e7ef6129edfd2a2ce17ddc544e6833c61f2f/src.renderer/tool/lt/IntGridTool.hx#L18

**Comment by deepnight** [comment]
Thanks for reporting, I'll fix that in next major update 👍
