### ISSUE TITLE
Crash: Switching to an int layer when editing a path

### ISSUE THREAD

**Issue by SecretPocketCat** [deepnight/ldtk#267]
Expected:  
Editing a path/point[] array, then switching to a different layer ends the path editing.

Actual:
The path editing UI stays active, but the editor crashes when clicking with the different layer selected.  

BTW. the crash UI is really neat.

Stack:
```
LDtk version: 0.6.0
Cannot read property 'getFieldInstance' of null
TypeError
TypeError: Cannot read property 'getFieldInstance' of null
    at ui_FieldInstancesForm.fieldInstGetter (file:///C:/Users/SecretPocketCat/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:94131:21)
    at ui_FieldInstancesForm.renderForm (file:///C:/Users/SecretPocketCat/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:94746:19)
    at ui_FieldInstancesForm.onFieldChange (file:///C:/Users/SecretPocketCat/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:94727:8)
    at tool_PickPoint.t.onPick (file:///C:/Users/SecretPocketCat/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:94710:11)
    at tool_PickPoint.stopUsing (file:///C:/Users/SecretPocketCat/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:86032:9)
    at page_Editor.onMouseUp (file:///C:/Users/SecretPocketCat/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:82772:22)
    at HTMLBodyElement.<anonymous> (file:///C:/Users/SecretPocketCat/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:80892:10)
    at HTMLBodyElement.dispatch (C:\Users\SecretPocketCat\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:36324)
    at HTMLBodyElement.v.handle (C:\Users\SecretPocketCat\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:34317)
```
Processes:
```
#0 App
 |--- #5 page.Editor
       |--- #6 misc.FileWatcher
       |--- #7 ui.Cursor
       |--- #8 display.WorldRender
       |--- #9 display.LevelRender
       |--- #10 display.Camera
       |--- display.Rulers[--]
       |--- tool.SelectionTool[--]
       |--- tool.lt.DoNothing[--]
       |--- WorldTool
       |--- tool.PanView[--]
       |--- #16 Option watcher (singleLayerMode)
       |--- #17 Option watcher (grid)
       |--- #18 Option watcher (emptySpaceSelection)
       |--- #19 Option watcher (tileStacking)
       |--- tool.lt.EntityTool[--]
       |--- tool.lt.IntGridTool[--]
       |--- tool.PickPoint[--]
```

Log:
```
[WARNING]      Last chance for: World layout changed
[EVENT]        WorldSettingsChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Chunk1(#0)
[EVENT]        LevelSelected
[RENDER]       Rendered world level data.Level.Chunk1(#0)
[EVENT]        LevelSettingsChanged
[RENDER]       Rendered world level data.Level.Chunk1(#0)
[ERROR]        You can't remove last level.
[WARNING]      Full render requested
[RENDER]       Rendered level UI
[FILE]         Reading HTML template worldPanel from cache
[RENDER]       Rendered world level data.Level.Chunk1(#0)
[EVENT]        LevelSelected
[EVENT]        LevelAdded
[RENDER]       Rendered world level data.Level.Chunk1(#0)
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSelected
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSettingsChanged
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSelected
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSettingsChanged
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSelected
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSettingsChanged
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[WARNING]      Last chance for: World layout changed
[EVENT]        WorldSettingsChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Chunk1(#0)
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[WARNING]      Last chance for: World layout changed
[EVENT]        WorldSettingsChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Chunk1(#0)
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSelected
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSettingsChanged
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSelected
[RENDER]       Rendered world level data.Level.Chunk1(#0)
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSelected
[RENDER]       Rendered world level data.Level.Chunk1(#0)
[RENDER]       Rendered world level data.Level.Chunk12(#13)
[EVENT]        LevelSelected
```
[deadline.crash.ldtk.zip](https://github.com/deepnight/ldtk/files/5611354/deadline.crash.ldtk.zip)

**Comment by deepnight** [comment]
Thanks for reporting this one!

**Comment by SecretPocketCat** [comment]
No worries.
Thanks for fixing it so quickly. 😃
