### ISSUE TITLE
Saving Multiple Files Bug

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#332]
When saving multiple level files, I get a crash.
Perhaps it's a directory problem? Maybe the directory was trying to be accessed before it was created?
![image](https://user-images.githubusercontent.com/55564581/105549794-f689e400-5cb5-11eb-9fb8-cd692d3b1d4e.png)

My steps were: 
- Open the file
- Save without the "export multiple level files" option selected
- Select "export multiple level files" on
- Try saving but crashes

Some of my steps may be unrelated, but it was my process. 

Something interesting is that once I tried getting back into the file, saving was completely fine after that whether or not I had multiple levels option selected. Perhaps because the directory was already made and available this time compared to when there was no directory made?

This is the file I tested with (Example project). It's a 0.6.2 version file. (no relative image files, my bad)
[WorldMap_Free_layout.zip](https://github.com/deepnight/ldtk/files/5858728/WorldMap_Free_layout.zip)

Stack:
```
LDtk version: 0.7.0
ENOENT: no such file or directory, open 'C:/Users/cameo/Documents/_Personal/UnityProjects/LDtkToUnity/Assets/Samples/_LDtkExamples/WorldMap_Free_layout/0000-Entrance.ldtkl'
Error
Error: ENOENT: no such file or directory, open 'C:/Users/cameo/Documents/_Personal/UnityProjects/LDtkToUnity/Assets/Samples/_LDtkExamples/WorldMap_Free_layout/0000-Entrance.ldtkl'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1283:35)
    at Function.misc_JsTools.writeFileString (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:86011:13)
    at dn__$Delayer_Task.ops.push.cb (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:102889:21)
    at dn_Delayer.update (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:30118:20)
    at Function.dn_Process._doPreUpdate (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:42:12)
    at Function.dn_Process.updateAll (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:253:20)
    at Boot.update (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1637:14)
    at Boot.mainLoop (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1600:8)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 ui.Cursor
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- display.Rulers[--]
       |--- tool.SelectionTool[--]
       |--- tool.lt.DoNothing[--]
       |--- WorldTool
       |--- tool.PanView[--]
       |--- #14 Option watcher (singleLayerMode)
       |--- #15 Option watcher (grid)
       |--- #16 Option watcher (emptySpaceSelection)
       |--- #17 Option watcher (tileStacking)
       |--- tool.lt.DoNothing[--]
       |--- #28 ui.Tip
       |--- #30 ui.ProjectSaving
       |--- #31 ui.modal.Progress
             |--- #32 dn.Process
```

Log:
```
[RENDER]       Rendered world level data.Level.Entrance(#3)
[RENDER]       Rendered world level data.Level.Beneath(#4)
[RENDER]       Rendered world level data.Level.Dead_end_east(#29)
[RENDER]       Rendered world level data.Level.Dead_end_west(#30)
[RENDER]       Rendered world level data.Level.Surface(#40)
[RENDER]       Rendered world level data.Level.Pit(#41)
[RENDER]       Rendered world level data.Level.Hidden_cave(#42)
[SAVE]         [WorldMap_Free_layout] Preparing project saving...
[SAVE]         [WorldMap_Free_layout] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [WorldMap_Free_layout] => AutoLayers...
[SAVE]         [WorldMap_Free_layout] => SavingMainFile...
[SAVE]         [WorldMap_Free_layout]   Preparing SavingData...
[SAVE]         [WorldMap_Free_layout]   Writing C:/Users/cameo/Documents/_Personal/UnityProjects/LDtkToUnity/Assets/Samples/_LDtkExamples/WorldMap_Free_layout.ldtk...
[SAVE]         [WorldMap_Free_layout] => Done...
[SAVE]         [WorldMap_Free_layout] Saving complete (WorldMap_Free_layout.ldtk)
[FILE]         Saved WorldMap_Free_layout.ldtk.
[EVENT]        ProjectSaved
[FILE]         Loading HTML template editProject
[EVENT]        ProjectSettingsChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Large_room(#0)
[RENDER]       Rendered level UI
[RENDER]       Rendered world level data.Level.Secret_passage(#2)
[RENDER]       Rendered world level data.Level.Entrance(#3)
[RENDER]       Rendered world level data.Level.Beneath(#4)
[RENDER]       Rendered world level data.Level.Dead_end_east(#29)
[RENDER]       Rendered world level data.Level.Dead_end_west(#30)
[RENDER]       Rendered world level data.Level.Surface(#40)
[RENDER]       Rendered world level data.Level.Pit(#41)
[RENDER]       Rendered world level data.Level.Hidden_cave(#42)
[SAVE]         [WorldMap_Free_layout] Preparing project saving...
[SAVE]         [WorldMap_Free_layout] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [WorldMap_Free_layout] => AutoLayers...
[SAVE]         [WorldMap_Free_layout] => SavingMainFile...
[SAVE]         [WorldMap_Free_layout]   Preparing SavingData...
[SAVE]         [WorldMap_Free_layout]   Writing C:/Users/cameo/Documents/_Personal/UnityProjects/LDtkToUnity/Assets/Samples/_LDtkExamples/WorldMap_Free_layout.ldtk...
[SAVE]         [WorldMap_Free_layout] => SavingExternLevels...
[GENERAL]      "Saving levels", 9 operation(s):
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        ENOENT: no such file or directory, open 'C:/Users/cameo/Documents/_Personal/UnityProjects/LDtkToUnity/Assets/Samples/_LDtkExamples/WorldMap_Free_layout/0000-Entrance.ldtkl' (Error)
[ERROR]        Error: ENOENT: no such file or directory, open 'C:/Users/cameo/Documents/_Personal/UnityProjects/LDtkToUnity/Assets/Samples/_LDtkExamples/WorldMap_Free_layout/0000-Entrance.ldtkl'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1283:35)
    at Function.misc_JsTools.writeFileString (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:86011:13)
    at dn__$Delayer_Task.ops.push.cb (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:102889:21)
    at dn_Delayer.update (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:30118:20)
    at Function.dn_Process._doPreUpdate (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:42:12)
    at Function.dn_Process.updateAll (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:253:20)
    at Boot.update (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1637:14)
    at Boot.mainLoop (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1600:8))

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 ui.Cursor
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- display.Rulers[--]
       |--- tool.SelectionTool[--]
       |--- tool.lt.DoNothing[--]
       |--- WorldTool
       |--- tool.PanView[--]
       |--- #14 Option watcher (singleLayerMode)
       |--- #15 Option watcher (grid)
       |--- #16 Option watcher (emptySpaceSelection)
       |--- #17 Option watcher (tileStacking)
       |--- tool.lt.DoNothing[--]
       |--- #28 ui.Tip
       |--- #30 ui.ProjectSaving
       |--- #31 ui.modal.Progress
             |--- #32 dn.Process
 |--- #33 page.CrashReport

[FILE]         Creating dir C:/Users/cameo/Documents/_Personal/UnityProjects/LDtkToUnity/Assets/Samples/_LDtkExamples/WorldMap_Free_layout...
[FILE]         Creating dir C:/Users/cameo/Documents/_Personal/UnityProjects/LDtkToUnity/Assets/Samples/_LDtkExamples/WorldMap_Free_layout/backups...
[FILE]         Cleared all file watches
```

**Comment by jprochazk** [comment]
I experienced the same issue.

To reproduce:

1. Open the sample "Test_file_for_API_showing_all_features.ldtk"
2. Go to project settings, select "Save levels to separate files"
3. Click save as -> save to somewhere

The application crashes with:

Stack:
```
LDtk version: 0.7.0
ENOENT: no such file or directory, open 'C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test\test\0000-Level1.ldtkl'
Error
Error: ENOENT: no such file or directory, open 'C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test\test\0000-Level1.ldtkl'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1283:35)
    at Function.misc_JsTools.writeFileString (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:86011:13)
    at dn__$Delayer_Task.ops.push.cb (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:102889:21)
    at dn_Delayer.update (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:30118:20)
    at Function.dn_Process._doPreUpdate (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:42:12)
    at Function.dn_Process.updateAll (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:253:20)
    at Boot.update (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1637:14)
    at Boot.mainLoop (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1600:8)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 ui.Cursor
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- display.Rulers[--]
       |--- tool.SelectionTool[--]
       |--- tool.lt.DoNothing[--]
       |--- WorldTool
       |--- tool.PanView[--]
       |--- #14 Option watcher (singleLayerMode)
       |--- #15 Option watcher (grid)
       |--- #16 Option watcher (emptySpaceSelection)
       |--- #17 Option watcher (tileStacking)
       |--- tool.lt.IntGridTool[--]
       |--- #19 display.EntityRender
       |--- #20 display.EntityRender
       |--- #21 display.EntityRender
       |--- #22 display.EntityRender
       |--- #23 display.EntityRender
       |--- #24 display.EntityRender
       |--- #25 display.EntityRender
       |--- #26 display.EntityRender
       |--- #27 display.EntityRender
       |--- #30 ui.modal.panel.EditProject
       |--- #35 ui.Tip
       |--- #39 ui.ProjectSaving
       |--- #40 ui.modal.Progress
             |--- #41 dn.Process
```

Log:
```
[FILE]          -> pixelData: Ok
[EVENT]        TilesetDefChanged 31
[EVENT]        ProjectSelected
[RENDER]       Reset world render
[FILE]         Watching file: C:/Users/Honza/AppData/Local/Programs/ldtk/samples/Inca_front_by_Kronbits-extended.png
[FILE]         Watching file: C:/Users/Honza/AppData/Local/Programs/ldtk/samples/7Soul's RPG Graphics - Icons.png
[FILE]         Watching file: C:/Users/Honza/AppData/Local/Programs/ldtk/samples/Inca_back2_by_Kronbits.png
[RENDER]       Rendered world level data.Level.Level1(#0)
[RENDER]       Rendered level UI
[RENDER]       Rendered world level data.Level.Level2(#32)
[RENDER]       Rendered world level data.Level.Level3(#33)
[RENDER]       Rendered world level data.Level.Level4(#36)
[CACHE]        Caching image Inca_back2_by_Kronbits.png...
[FILE]         Loading HTML template editProject
[EVENT]        ProjectSettingsChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level1(#0)
[RENDER]       Rendered level UI
[RENDER]       Rendered world level data.Level.Level2(#32)
[RENDER]       Rendered world level data.Level.Level3(#33)
[RENDER]       Rendered world level data.Level.Level4(#36)
[FILE]         Remap project paths: C:/Users/Honza/AppData/Local/Programs/ldtk/samples => C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test
[FILE]         Remap file path: Inca_front_by_Kronbits-extended.png => ../Inca_front_by_Kronbits-extended.png
[FILE]         Remap file path: 7Soul's RPG Graphics - Icons.png => ../7Soul's RPG Graphics - Icons.png
[FILE]         Remap project paths: C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test => C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test
[FILE]         Remap file path: ../Inca_front_by_Kronbits-extended.png => ../Inca_front_by_Kronbits-extended.png
[FILE]         Remap file path: ../7Soul's RPG Graphics - Icons.png => ../7Soul's RPG Graphics - Icons.png
[SAVE]         [test] Preparing project saving...
[CACHE]        Garbaging unused image Inca_front_by_Kronbits-extended.png...
[CACHE]        Disposing cached image Inca_front_by_Kronbits-extended.png...
[CACHE]        Garbaging unused image 7Soul's RPG Graphics - Icons.png...
[CACHE]        Disposing cached image 7Soul's RPG Graphics - Icons.png...
[SAVE]         [test] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [test] => AutoLayers...
[SAVE]         [test] => SavingMainFile...
[SAVE]         [test]   Preparing SavingData...
[SAVE]         [test]   Writing C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test\test.ldtk...
[SAVE]         [test] => SavingExternLevels...
[GENERAL]      "Saving levels", 4 operation(s):
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        ENOENT: no such file or directory, open 'C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test\test\0000-Level1.ldtkl' (Error)
[ERROR]        Error: ENOENT: no such file or directory, open 'C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test\test\0000-Level1.ldtkl'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1283:35)
    at Function.misc_JsTools.writeFileString (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:86011:13)
    at dn__$Delayer_Task.ops.push.cb (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:102889:21)
    at dn_Delayer.update (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:30118:20)
    at Function.dn_Process._doPreUpdate (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:42:12)
    at Function.dn_Process.updateAll (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:253:20)
    at Boot.update (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1637:14)
    at Boot.mainLoop (file:///C:/Users/Honza/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1600:8))

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 ui.Cursor
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- display.Rulers[--]
       |--- tool.SelectionTool[--]
       |--- tool.lt.DoNothing[--]
       |--- WorldTool
       |--- tool.PanView[--]
       |--- #14 Option watcher (singleLayerMode)
       |--- #15 Option watcher (grid)
       |--- #16 Option watcher (emptySpaceSelection)
       |--- #17 Option watcher (tileStacking)
       |--- tool.lt.IntGridTool[--]
       |--- #19 display.EntityRender
       |--- #20 display.EntityRender
       |--- #21 display.EntityRender
       |--- #22 display.EntityRender
       |--- #23 display.EntityRender
       |--- #24 display.EntityRender
       |--- #25 display.EntityRender
       |--- #26 display.EntityRender
       |--- #27 display.EntityRender
       |--- #30 ui.modal.panel.EditProject
       |--- #35 ui.Tip
       |--- #39 ui.ProjectSaving
       |--- #40 ui.modal.Progress
             |--- #41 dn.Process
 |--- #42 page.CrashReport

[FILE]         Creating dir C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test\test...
[FILE]         Creating dir C:\Users\Honza\AppData\Local\Programs\ldtk\samples\test\test\backups...
[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
I'll check that tomorrow 🤔

**Comment by Cammin** [comment]
Additionally, If I have not saved as multiple levels before, and attempt to access the directory with the folder button, the directory does not exist, likely because the directory was not created yet. So a solution could be to only display the button if the directory exists?
![image](https://user-images.githubusercontent.com/55564581/105642358-206e1280-5e3e-11eb-8a21-3e9767c658d9.png)

Good luck with the fix, always glad to help out where I can :)

**Comment by deepnight** [comment]
It'll be fixed today, sorry about the inconvenience!
