### ISSUE TITLE
Issue when trying to add a new value to an IntGrid

### ISSUE THREAD

**Issue by gusg21** [deepnight/ldtk#347]
As far as I can remember I was just setting up a new project and I tried to add a new value to an IntGrid. Not sure what else to say, I wasn't doing anything out of the ordinary 🤷 

Here's the stack:

Stack:
```
LDtk version: 0.7.1
Cannot read property 'relPath' of null
TypeError
TypeError: Cannot read property 'relPath' of null
    at file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:28831:22
    at data_Level.iterateLayerInstancesInRenderOrder (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:13144:4)
    at display_WorldRender.renderLevel (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:28806:5)
    at display_WorldRender.postUpdate (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:29688:10)
    at Function.dn_Process._doPostUpdate (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:118:4)
    at Function.dn_Process.updateAll (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:296:20)
    at Boot.update (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1596:14)
    at Boot.mainLoop (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1559:8)
    at hxd_System.browserLoop (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:65573:14)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 ui.Cursor
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- display.Rulers[--]
       |--- tool.SelectionTool[--]
       |--- tool.lt.DoNothing[--]
       |--- WorldTool
       |--- tool.PanView[--]
       |--- #14 Option watcher (singleLayerMode)
       |--- #15 Option watcher (grid)
       |--- #16 Option watcher (emptySpaceSelection)
       |--- #17 Option watcher (tileStacking)
       |--- tool.lt.IntGridTool[--]
       |--- #101 ui.modal.panel.EditLayerDefs
       |--- tool.lt.IntGridTool[--]
```

Log:
```
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level(#0)
[ERROR]        missing autoTilesCache in Instance[#1,BGAuto:AutoLayer]
[WARNING]      Full render requested
[FILE]         Reading HTML template editProject from cache
[FILE]         Loading HTML template colorPicker
[EVENT]        ProjectSettingsChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level(#0)
[ERROR]        missing autoTilesCache in Instance[#1,BGAuto:AutoLayer]
[RENDER]       Rendered level UI
[FILE]         Reading HTML template colorPicker from cache
[EVENT]        ProjectSettingsChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level(#0)
[ERROR]        missing autoTilesCache in Instance[#1,BGAuto:AutoLayer]
[RENDER]       Rendered level UI
[SAVE]         [World] Preparing project saving...
[SAVE]         [World] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [World] => AutoLayers...
[GENERAL]      "Updating auto-layers...", 1 operation(s):
[WARNING]      All rules applied in Instance[#1,BGAuto:AutoLayer]
[GENERAL]      Done "Updating auto-layers..." (0.02s)
[SAVE]         [World] => SavingMainFile...
[SAVE]         [World]   Preparing SavingData...
[SAVE]         [World]   Writing D:\Unity\Pixel Perfect\Assets\World\World.ldtk...
[SAVE]         [World] => Done...
[SAVE]         [World] Saving complete (World.ldtk)
[FILE]         Saved World.ldtk.
[EVENT]        ProjectSaved
[FILE]         Reading HTML template editLayerDefs from cache
[FILE]         Loading HTML template editEntityDefs
[FILE]         Loading HTML template editEnums
[FILE]         Reading HTML template editTilesetDefs from cache
[FILE]         Reading HTML template editEntityDefs from cache
[FILE]         Reading HTML template editLayerDefs from cache
[EVENT]        LayerDefChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level(#0)
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'relPath' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'relPath' of null
    at file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:28831:22
    at data_Level.iterateLayerInstancesInRenderOrder (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:13144:4)
    at display_WorldRender.renderLevel (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:28806:5)
    at display_WorldRender.postUpdate (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:29688:10)
    at Function.dn_Process._doPostUpdate (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:118:4)
    at Function.dn_Process.updateAll (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:296:20)
    at Boot.update (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1596:14)
    at Boot.mainLoop (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1559:8)
    at hxd_System.browserLoop (file:///C:/Users/gus/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:65573:14))

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 ui.Cursor
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- display.Rulers[--]
       |--- tool.SelectionTool[--]
       |--- tool.lt.DoNothing[--]
       |--- WorldTool
       |--- tool.PanView[--]
       |--- #14 Option watcher (singleLayerMode)
       |--- #15 Option watcher (grid)
       |--- #16 Option watcher (emptySpaceSelection)
       |--- #17 Option watcher (tileStacking)
       |--- tool.lt.IntGridTool[--]
       |--- #101 ui.modal.panel.EditLayerDefs
       |--- tool.lt.IntGridTool[--]
 |--- #104 page.CrashReport

[FILE]         Creating dir D:\Unity\Pixel Perfect\Assets\World\World...
[FILE]         Creating dir D:\Unity\Pixel Perfect\Assets\World\World\backups...
[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Sorry about that, I'll check it out 🤔

**Comment by deepnight** [comment]
Is the problem still happening in **0.7.2**?

**Comment by gusg21** [comment]
Doesn't seem to be - thank you! I'll reopen if it happens again.
