### ISSUE TITLE
Crash on mouseUp when placing Point type field

### ISSUE THREAD

**Issue by volnt** [deepnight/ldtk#412]
Crash on mouseUp when placing Point type field on the 8.1 Linux build.

![image](https://user-images.githubusercontent.com/2411932/110176485-a600bd00-7e03-11eb-939b-b023b87a9dbb.png)

To reproduce you can test with the following minimal ldtk file : [test.zip](https://github.com/deepnight/ldtk/files/6093528/test.zip)

Place an Entity "Entity", click on "--NONE--" in the Entity attributes to update the attribute "Point" and click anywhere on the map : 

![image](https://user-images.githubusercontent.com/2411932/110176925-61c1ec80-7e04-11eb-9c26-f2d353f929df.png)

LDtk should crash on mouseUp.

<details>
  <summary>Here is the full report</summary>

Stack:

```
LDtk version: 0.8.1-64bits
Cannot read property 'cx' of null
TypeError
TypeError: Cannot read property 'cx' of null
    at tool_PickPoint.t.canPick (file:///tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/renderer.js:116509:34)
    at tool_PickPoint.stopUsing (file:///tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/renderer.js:100891:18)
    at page_Editor.onMouseUp (file:///tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/renderer.js:94561:22)
    at HTMLBodyElement.<anonymous> (file:///tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/renderer.js:92622:10)
    at HTMLBodyElement.dispatch (/tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/jquery-git.min.js:2:36324)
    at HTMLBodyElement.v.handle (/tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/jquery-git.min.js:2:34317)
```

Processes:

```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #34 ui.Notification
       |--- #35 ui.EntityInstanceEditor
       |--- #36 tool.ResizeTool[--]
       |--- #37 display.EntityRender
       |--- #38 tool.PickPoint[--]
```

Log:

```
[...]
[FILE]         Emptying dir /home/volnt/dev/alien-shepherd/res/world/test (onlyExts=[ldtkl])...
[SAVE]         [test] => Done...
[SAVE]         [test] Saving complete (test.ldtk)
[FILE]         Saved "test.ldtk".
[EVENT]        ProjectSaved
[EVENT]        EntityInstanceAdded 2
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from /tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'cx' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'cx' of null
    at tool_PickPoint.t.canPick (file:///tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/renderer.js:116509:34)
    at tool_PickPoint.stopUsing (file:///tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/renderer.js:100891:18)
    at page_Editor.onMouseUp (file:///tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/renderer.js:94561:22)
    at HTMLBodyElement.<anonymous> (file:///tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/renderer.js:92622:10)
    at HTMLBodyElement.dispatch (/tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/jquery-git.min.js:2:36324)
    at HTMLBodyElement.v.handle (/tmp/.mount_ldtkKE9gZ5/resources/app.asar/assets/js/jquery-git.min.js:2:34317))

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #34 ui.Notification
       |--- #35 ui.EntityInstanceEditor
       |--- #36 tool.ResizeTool[--]
       |--- #37 display.EntityRender
       |--- #38 tool.PickPoint[--]
 |--- #39 page.CrashReport

[FILE]         Cleared all file watches
```

</details>

**Comment by deepnight** [comment]
Thanks for reporting, it will be fixed in 0.8.2 .
Sorry for the inconvenience!
