### ISSUE TITLE
Cannot read property 'getInt32' of null

### ISSUE THREAD

**Issue by qkdreyer** [deepnight/ldtk#427]
Stack:
```
LDtk version: 0.8.1-64bits
Cannot read property 'getInt32' of null
TypeError
TypeError: Cannot read property 'getInt32' of null
    at hxd_Pixels.getPixel (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:68927:23)
    at data_def_TilesetDef._parseTilePixels (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:19489:25)
    at dn__$Delayer_Task.ops.push.cb (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:19627:14)
    at dn_Delayer.update (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:33598:20)
    at Function.dn_Process._doPreUpdate (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:88:12)
    at Function.dn_Process.updateAll (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:697:20)
    at Boot.update (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:2792:14)
    at Boot.mainLoop (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:2755:8)
    at hxd_System.browserLoop (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:69802:14)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.EntityTool [PAUSED][--]
       |--- #118 tool.lt.EntityTool [PAUSED][--]
       |--- #119 tool.lt.IntGridTool[--]
       |--- #120 tool.lt.IntGridTool [PAUSED][--]
       |--- #139 ui.Tip
       |--- #159 ui.modal.panel.EditTilesetDefs
       |--- #162 display.EntityRender
       |--- #163 display.EntityRender
       |--- #164 display.EntityRender
       |--- #165 display.EntityRender
       |--- #166 display.EntityRender
       |--- #167 display.EntityRender
       |--- #168 display.EntityRender
       |--- #169 display.EntityRender
       |--- #170 display.EntityRender
       |--- #171 display.EntityRender
       |--- #172 display.EntityRender
       |--- #173 display.EntityRender
       |--- #174 display.EntityRender
       |--- #175 display.EntityRender
       |--- #176 display.EntityRender
       |--- #177 display.EntityRender
       |--- #178 display.EntityRender
       |--- #179 display.EntityRender
       |--- #180 display.EntityRender
       |--- #181 display.EntityRender
       |--- #182 display.EntityRender
       |--- #183 display.EntityRender
       |--- #184 display.EntityRender
       |--- #185 display.EntityRender
       |--- #186 display.EntityRender
       |--- #187 display.EntityRender
       |--- #188 display.EntityRender
       |--- #189 display.EntityRender
       |--- #190 display.EntityRender
       |--- #191 display.EntityRender
       |--- #192 display.EntityRender
       |--- #193 display.EntityRender
       |--- #194 display.EntityRender
       |--- #195 display.EntityRender
       |--- #196 display.EntityRender
       |--- #197 display.EntityRender
       |--- #198 display.EntityRender
       |--- #199 display.EntityRender
       |--- #200 display.EntityRender
       |--- #201 display.EntityRender
       |--- #202 display.EntityRender
       |--- #203 display.EntityRender
       |--- #204 display.EntityRender
       |--- #205 display.EntityRender
       |--- #206 display.EntityRender
       |--- #207 display.EntityRender
       |--- #208 display.EntityRender
       |--- #209 display.EntityRender
       |--- #210 display.EntityRender
       |--- #211 display.EntityRender
       |--- #212 display.EntityRender
       |--- #213 display.EntityRender
       |--- #214 display.EntityRender
       |--- #215 display.EntityRender
       |--- #216 display.EntityRender
       |--- #217 display.EntityRender
       |--- #218 display.EntityRender
       |--- #219 display.EntityRender
       |--- #220 display.EntityRender
       |--- #221 display.EntityRender
       |--- #222 display.EntityRender
       |--- #223 display.EntityRender
       |--- #224 display.EntityRender
       |--- #225 display.EntityRender
       |--- #226 display.EntityRender
       |--- #227 display.EntityRender
       |--- #228 display.EntityRender
       |--- #229 display.EntityRender
       |--- #230 display.EntityRender
       |--- #231 display.EntityRender
       |--- #232 display.EntityRender
       |--- #233 display.EntityRender
       |--- #234 display.EntityRender
       |--- #235 display.EntityRender
       |--- #236 display.EntityRender
       |--- #237 display.EntityRender
       |--- #238 display.EntityRender
       |--- #239 display.EntityRender
       |--- #240 display.EntityRender
       |--- #241 display.EntityRender
       |--- #242 display.EntityRender
       |--- #243 display.EntityRender
       |--- #244 display.EntityRender
       |--- #245 display.EntityRender
       |--- #246 display.EntityRender
       |--- #247 display.EntityRender
       |--- #248 display.EntityRender
       |--- #249 display.EntityRender
       |--- #250 display.EntityRender
       |--- #251 display.EntityRender
       |--- #252 display.EntityRender
       |--- #253 display.EntityRender
       |--- #254 display.EntityRender
       |--- #255 display.EntityRender
       |--- #256 display.EntityRender
       |--- #257 display.EntityRender
       |--- #258 display.EntityRender
       |--- #259 display.EntityRender
       |--- #260 display.EntityRender
       |--- #261 display.EntityRender
       |--- #262 display.EntityRender
       |--- #263 display.EntityRender
       |--- #264 display.EntityRender
       |--- #265 display.EntityRender
       |--- #271 ui.modal.Progress
             |--- #272 dn.Process
       |--- #273 ui.Notification
       |--- #274 ui.modal.Progress
             |--- #275 dn.Process
       |--- #276 ui.modal.Progress
             |--- #277 dn.Process
       |--- #278 ui.modal.Progress
             |--- #279 dn.Process
```

Log:
```
[GENERAL]      Done "Initializing pixel data cache for "collisions.png"" (0.51s)
[EVENT]        TilesetDefPixelDataCacheRebuilt 3
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Grass(#0)
[EVENT]        TilesetDefAdded 114
[EVENT]        TilesetDefChanged 114
[EVENT]        TilesetDefChanged 114
[FILE]         Loading atlas: /Users/qkdreyer/Dev/creamy-viking-1/res/world/collisions.png
[FILE]         Loading atlas image: collisions.png...
[FILE]          -> Loaded 17751 bytes.
[FILE]          -> Decoded 256x256 pixels.
[FILE]         Stopped watching: /Users/qkdreyer/Dev/creamy-viking-1/res/world/collisions.png
[FILE]         Watching file: /Users/qkdreyer/Dev/creamy-viking-1/res/world/collisions.png
[EVENT]        TilesetDefChanged 114
[GENERAL]      Init pixel data cache for collisions.png
[GENERAL]      "Initializing pixel data cache for "collisions.png"", 4 operation(s):
[FILE]         Changed on disk: /Users/qkdreyer/Dev/creamy-viking-1/res/world/collisions.png
[CACHE]        Reloading cached image collisions.png...
[CACHE]        Disposing cached image collisions.png...
[CACHE]        Caching image collisions.png...
[FILE]         Reloading tileset: Collisions2 path=collisions.png
[FILE]         Loading atlas image: collisions.png...
[FILE]          -> Loaded 30006 bytes.
[FILE]          -> Decoded 256x256 pixels.
[GENERAL]      Tileset remapping...
[FILE]          -> Reload result: Ok
[FILE]          -> pixelData: Ok
[GENERAL]      Init pixel data cache for collisions.png
[GENERAL]      "Initializing pixel data cache for "collisions.png"", 4 operation(s):
[EVENT]        TilesetDefChanged 3
[FILE]         Reloading tileset: Collisions path=collisions.png
[FILE]         Loading atlas image: collisions.png...
[FILE]          -> Loaded 30006 bytes.
[FILE]          -> Decoded 256x256 pixels.
[GENERAL]      Tileset remapping...
[FILE]          -> Reload result: Ok
[FILE]          -> pixelData: Ok
[GENERAL]      Init pixel data cache for collisions.png
[GENERAL]      "Initializing pixel data cache for "collisions.png"", 4 operation(s):
[EVENT]        TilesetDefChanged 114
[GENERAL]      Init pixel data cache for collisions.png
[GENERAL]      "Initializing pixel data cache for "collisions.png"", 4 operation(s):
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from /Applications/LDtk.app/Contents/Resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'getInt32' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'getInt32' of null
    at hxd_Pixels.getPixel (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:68927:23)
    at data_def_TilesetDef._parseTilePixels (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:19489:25)
    at dn__$Delayer_Task.ops.push.cb (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:19627:14)
    at dn_Delayer.update (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:33598:20)
    at Function.dn_Process._doPreUpdate (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:88:12)
    at Function.dn_Process.updateAll (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:697:20)
    at Boot.update (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:2792:14)
    at Boot.mainLoop (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:2755:8)
    at hxd_System.browserLoop (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:69802:14))

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.EntityTool [PAUSED][--]
       |--- #118 tool.lt.EntityTool [PAUSED][--]
       |--- #119 tool.lt.IntGridTool[--]
       |--- #120 tool.lt.IntGridTool [PAUSED][--]
       |--- #139 ui.Tip
       |--- #159 ui.modal.panel.EditTilesetDefs
       |--- #162 display.EntityRender
       |--- #163 display.EntityRender
       |--- #164 display.EntityRender
       |--- #165 display.EntityRender
       |--- #166 display.EntityRender
       |--- #167 display.EntityRender
       |--- #168 display.EntityRender
       |--- #169 display.EntityRender
       |--- #170 display.EntityRender
       |--- #171 display.EntityRender
       |--- #172 display.EntityRender
       |--- #173 display.EntityRender
       |--- #174 display.EntityRender
       |--- #175 display.EntityRender
       |--- #176 display.EntityRender
       |--- #177 display.EntityRender
       |--- #178 display.EntityRender
       |--- #179 display.EntityRender
       |--- #180 display.EntityRender
       |--- #181 display.EntityRender
       |--- #182 display.EntityRender
       |--- #183 display.EntityRender
       |--- #184 display.EntityRender
       |--- #185 display.EntityRender
       |--- #186 display.EntityRender
       |--- #187 display.EntityRender
       |--- #188 display.EntityRender
       |--- #189 display.EntityRender
       |--- #190 display.EntityRender
       |--- #191 display.EntityRender
       |--- #192 display.EntityRender
       |--- #193 display.EntityRender
       |--- #194 display.EntityRender
       |--- #195 display.EntityRender
       |--- #196 display.EntityRender
       |--- #197 display.EntityRender
       |--- #198 display.EntityRender
       |--- #199 display.EntityRender
       |--- #200 display.EntityRender
       |--- #201 display.EntityRender
       |--- #202 display.EntityRender
       |--- #203 display.EntityRender
       |--- #204 display.EntityRender
       |--- #205 display.EntityRender
       |--- #206 display.EntityRender
       |--- #207 display.EntityRender
       |--- #208 display.EntityRender
       |--- #209 display.EntityRender
       |--- #210 display.EntityRender
       |--- #211 display.EntityRender
       |--- #212 display.EntityRender
       |--- #213 display.EntityRender
       |--- #214 display.EntityRender
       |--- #215 display.EntityRender
       |--- #216 display.EntityRender
       |--- #217 display.EntityRender
       |--- #218 display.EntityRender
       |--- #219 display.EntityRender
       |--- #220 display.EntityRender
       |--- #221 display.EntityRender
       |--- #222 display.EntityRender
       |--- #223 display.EntityRender
       |--- #224 display.EntityRender
       |--- #225 display.EntityRender
       |--- #226 display.EntityRender
       |--- #227 display.EntityRender
       |--- #228 display.EntityRender
       |--- #229 display.EntityRender
       |--- #230 display.EntityRender
       |--- #231 display.EntityRender
       |--- #232 display.EntityRender
       |--- #233 display.EntityRender
       |--- #234 display.EntityRender
       |--- #235 display.EntityRender
       |--- #236 display.EntityRender
       |--- #237 display.EntityRender
       |--- #238 display.EntityRender
       |--- #239 display.EntityRender
       |--- #240 display.EntityRender
       |--- #241 display.EntityRender
       |--- #242 display.EntityRender
       |--- #243 display.EntityRender
       |--- #244 display.EntityRender
       |--- #245 display.EntityRender
       |--- #246 display.EntityRender
       |--- #247 display.EntityRender
       |--- #248 display.EntityRender
       |--- #249 display.EntityRender
       |--- #250 display.EntityRender
       |--- #251 display.EntityRender
       |--- #252 display.EntityRender
       |--- #253 display.EntityRender
       |--- #254 display.EntityRender
       |--- #255 display.EntityRender
       |--- #256 display.EntityRender
       |--- #257 display.EntityRender
       |--- #258 display.EntityRender
       |--- #259 display.EntityRender
       |--- #260 display.EntityRender
       |--- #261 display.EntityRender
       |--- #262 display.EntityRender
       |--- #263 display.EntityRender
       |--- #264 display.EntityRender
       |--- #265 display.EntityRender
       |--- #271 ui.modal.Progress
             |--- #272 dn.Process
       |--- #273 ui.Notification
       |--- #274 ui.modal.Progress
             |--- #275 dn.Process
       |--- #276 ui.modal.Progress
             |--- #277 dn.Process
       |--- #278 ui.modal.Progress
             |--- #279 dn.Process
 |--- #280 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by ChoiysApple** [comment]
Same issue here

**System:** `MacOS 12.1` 

**Situation:** I was browsing tile png files to add tileset from `LDtk.app/Contents/samples/atlas` after adding one tileset and this happened

**Stack:**
```
LDtk version: 0.9.3-64bits
Cannot read property 'getInt32' of null
TypeError
TypeError: Cannot read property 'getInt32' of null
    at hxd_Pixels.getPixel (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:115095:23)
    at data_def_TilesetDef._parseTilePixels (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:24028:25)
    at dn__$Delayer_Task.ops.push.cb (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:24213:14)
    at dn_Delayer.update (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:48145:20)
    at Function.dn_Process._doPreUpdate (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:111:12)
    at Function.dn_Process.updateAll (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:720:20)
    at Boot.update (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:4050:14)
    at Boot.mainLoop (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:4012:8)
    at hxd_System.browserLoop (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:116203:14)
```
Processes:
```
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 display.WorldRender
       |--- #5 display.LevelRender
       |--- #6 display.Camera
       |--- #7 display.Rulers[--]
       |--- #8 tool.SelectionTool[--]
       |--- #9 tool.lt.DoNothing[--]
       |--- #10 WorldTool
       |--- #11 tool.PanView[--]
       |--- #13 ui.modal.panel.EditTilesetDefs
       |--- #26 ui.Notification
       |--- #27 ui.modal.Progress
             |--- #28 dn.Process
       |--- #29 ui.Notification
       |--- #30 ui.modal.Progress
             |--- #31 dn.Process
```

Log:
```
[FILE]         Loading atlas image: atlas/SunnyLand_by_Ansimuz-extended.png...
[FILE]          -> Loaded 15116 bytes.
[FILE]          -> Decoded 368x336 pixels.
[FILE]         Watching file: /Applications/LDtk.app/Contents/samples/atlas/SunnyLand_by_Ansimuz-extended.png
[EVENT]        TilesetDefChanged 1
[GENERAL]      Init pixel data cache for atlas/SunnyLand_by_Ansimuz-extended.png
[GENERAL]      "Initializing pixel data cache for "SunnyLand_by_Ansimuz-extended.png"", 21 operation(s):
[GENERAL]      Done "Initializing pixel data cache for "SunnyLand_by_Ansimuz-extended.png"" (0.17s)
[EVENT]        TilesetDefPixelDataCacheRebuilt 1
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level_0(#0)
[EVENT]        TilesetDefAdded 2
[FILE]         Changed on disk: /Applications/LDtk.app/Contents/samples/atlas/SunnyLand_by_Ansimuz-extended.png
[CACHE]        Reloading cached image atlas/SunnyLand_by_Ansimuz-extended.png...
[CACHE]        Disposing cached image atlas/SunnyLand_by_Ansimuz-extended.png...
[CACHE]        Caching image atlas/SunnyLand_by_Ansimuz-extended.png...
[CACHE]         -> identified as Png
[FILE]         Reloading tileset: SunnyLand_by_Ansimuz_extended path=atlas/SunnyLand_by_Ansimuz-extended.png
[FILE]         Loading atlas image: atlas/SunnyLand_by_Ansimuz-extended.png...
[FILE]          -> Loaded 15116 bytes.
[FILE]          -> Decoded 368x336 pixels.
[GENERAL]      Tileset remapping...
[FILE]          -> Reload result: Ok
[FILE]          -> pixelData: Ok
[GENERAL]      Init pixel data cache for atlas/SunnyLand_by_Ansimuz-extended.png
[GENERAL]      "Initializing pixel data cache for "SunnyLand_by_Ansimuz-extended.png"", 21 operation(s):
[EVENT]        TilesetDefChanged 1
[FILE]         Changed on disk: /Applications/LDtk.app/Contents/samples/atlas/SunnyLand_by_Ansimuz-extended.png
[CACHE]        Reloading cached image atlas/SunnyLand_by_Ansimuz-extended.png...
[CACHE]        Disposing cached image atlas/SunnyLand_by_Ansimuz-extended.png...
[CACHE]        Caching image atlas/SunnyLand_by_Ansimuz-extended.png...
[CACHE]         -> identified as Png
[FILE]         Reloading tileset: SunnyLand_by_Ansimuz_extended path=atlas/SunnyLand_by_Ansimuz-extended.png
[FILE]         Loading atlas image: atlas/SunnyLand_by_Ansimuz-extended.png...
[FILE]          -> Loaded 15116 bytes.
[FILE]          -> Decoded 368x336 pixels.
[GENERAL]      Tileset remapping...
[FILE]          -> Reload result: Ok
[FILE]          -> pixelData: Ok
[GENERAL]      Init pixel data cache for atlas/SunnyLand_by_Ansimuz-extended.png
[GENERAL]      "Initializing pixel data cache for "SunnyLand_by_Ansimuz-extended.png"", 21 operation(s):
[EVENT]        TilesetDefChanged 1
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from /Applications/LDtk.app/Contents/Resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'getInt32' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'getInt32' of null
    at hxd_Pixels.getPixel (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:115095:23)
    at data_def_TilesetDef._parseTilePixels (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:24028:25)
    at dn__$Delayer_Task.ops.push.cb (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:24213:14)
    at dn_Delayer.update (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:48145:20)
    at Function.dn_Process._doPreUpdate (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:111:12)
    at Function.dn_Process.updateAll (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:720:20)
    at Boot.update (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:4050:14)
    at Boot.mainLoop (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:4012:8)
    at hxd_System.browserLoop (file:///Applications/LDtk.app/Contents/Resources/app.asar/assets/js/renderer.js:116203:14)

[GENERAL]      
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 display.WorldRender
       |--- #5 display.LevelRender
       |--- #6 display.Camera
       |--- #7 display.Rulers[--]
       |--- #8 tool.SelectionTool[--]
       |--- #9 tool.lt.DoNothing[--]
       |--- #10 WorldTool
       |--- #11 tool.PanView[--]
       |--- #13 ui.modal.panel.EditTilesetDefs
       |--- #26 ui.Notification
       |--- #27 ui.modal.Progress
             |--- #28 dn.Process
       |--- #29 ui.Notification
       |--- #30 ui.modal.Progress
             |--- #31 dn.Process
 |--- #32 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Thanks for reporting, it should be fixed in next update.
