### ISSUE TITLE
Cannot read property 'cx' of null (TypeError)

### ISSUE THREAD

**Issue by jaybels83** [deepnight/ldtk#434]
I get this error trying to use a point field for an entity and assigning the point variable in the editor.

This doesn't happen when I use a point array.

Stack:
```
LDtk version: 0.8.1-64bits
Cannot read property 'cx' of null
TypeError
TypeError: Cannot read property 'cx' of null
    at tool_PickPoint.t.canPick (file:///C:/Users/mbbai/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:116509:34)
    at tool_PickPoint.stopUsing (file:///C:/Users/mbbai/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:100891:18)
    at page_Editor.onMouseUp (file:///C:/Users/mbbai/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:94561:22)
    at HTMLBodyElement.<anonymous> (file:///C:/Users/mbbai/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:92622:10)
    at HTMLBodyElement.dispatch (C:\Users\mbbai\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:36324)
    at HTMLBodyElement.v.handle (C:\Users\mbbai\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:34317)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.EntityTool[--]
       |--- #568 ui.EntityInstanceEditor
       |--- #569 tool.ResizeTool[--]
       |--- #570 display.EntityRender
       |--- #571 display.EntityRender
       |--- #572 display.EntityRender
       |--- #573 display.EntityRender
       |--- #574 display.EntityRender
       |--- #575 display.EntityRender
       |--- #576 display.EntityRender
       |--- #577 display.EntityRender
       |--- #578 display.EntityRender
       |--- #579 display.EntityRender
       |--- #580 display.EntityRender
       |--- #581 display.EntityRender
       |--- #582 display.EntityRender
       |--- #583 display.EntityRender
       |--- #584 display.EntityRender
       |--- #585 display.EntityRender
       |--- #586 display.EntityRender
       |--- #587 display.EntityRender
       |--- #588 display.EntityRender
       |--- #589 display.EntityRender
       |--- #590 display.EntityRender
       |--- #591 display.EntityRender
       |--- #592 display.EntityRender
       |--- #593 display.EntityRender
       |--- #594 tool.PickPoint[--]
```

Log:
```
[FILE]         Saved "Level Editor.json".
[EVENT]        ProjectSaved
[FILE]         Reading HTML template editProject from cache
[FILE]         Remap project paths: D:\Unity\Projects\Udemy LDtk\Assets\Levels => D:\Unity\Projects\Udemy LDtk\Assets\Levels
[FILE]         Remap file path: Assets/Sunnyland.png => Assets/Sunnyland.png
[SAVE]         [Level Editor] Preparing project saving...
[SAVE]         [Level Editor] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [Level Editor] => AutoLayers...
[SAVE]         [Level Editor] => SavingMainFile...
[SAVE]         [Level Editor]   Preparing SavingData...
[SAVE]         [Level Editor]   Writing D:\Unity\Projects\Udemy LDtk\Assets\Levels\Level Editor.ldtk...
[SAVE]         [Level Editor] => SavingExternLevels...
[FILE]         Emptying dir D:\Unity\Projects\Udemy LDtk\Assets\Levels\Level Editor (onlyExts=[ldtkl])...
[GENERAL]      "Saving levels", 1 operation(s):
[GENERAL]      Done "Saving levels" (0.01s)
[SAVE]         [Level Editor] => Done...
[SAVE]         [Level Editor] Saving complete (Level Editor.ldtk)
[FILE]         Saved "Level Editor.ldtk".
[EVENT]        ProjectSaved
[SAVE]         [Level Editor] Preparing project saving...
[SAVE]         [Level Editor] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [Level Editor] => AutoLayers...
[SAVE]         [Level Editor] => SavingMainFile...
[SAVE]         [Level Editor]   Preparing SavingData...
[SAVE]         [Level Editor]   Writing D:\Unity\Projects\Udemy LDtk\Assets\Levels\Level Editor.ldtk...
[SAVE]         [Level Editor] => SavingExternLevels...
[FILE]         Emptying dir D:\Unity\Projects\Udemy LDtk\Assets\Levels\Level Editor (onlyExts=[ldtkl])...
[GENERAL]      "Saving levels", 1 operation(s):
[GENERAL]      Done "Saving levels" (0.02s)
[SAVE]         [Level Editor] => Done...
[SAVE]         [Level Editor] Saving complete (Level Editor.ldtk)
[FILE]         Saved "Level Editor.ldtk".
[EVENT]        ProjectSaved
[FILE]         Reading HTML template editEntityDefs from cache
[FILE]         Reading HTML template fieldDefsForm from cache
[WARNING]      Last chance for: Field Patrol deleted
[EVENT]        FieldDefRemoved Patrol
[EVENT]        FieldDefAdded Point
[EVENT]        FieldDefChanged PatrolTo
[EVENT]        EntityInstanceAdded 60
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/mbbai/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'cx' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'cx' of null
    at tool_PickPoint.t.canPick (file:///C:/Users/mbbai/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:116509:34)
    at tool_PickPoint.stopUsing (file:///C:/Users/mbbai/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:100891:18)
    at page_Editor.onMouseUp (file:///C:/Users/mbbai/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:94561:22)
    at HTMLBodyElement.<anonymous> (file:///C:/Users/mbbai/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:92622:10)
    at HTMLBodyElement.dispatch (C:\Users\mbbai\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:36324)
    at HTMLBodyElement.v.handle (C:\Users\mbbai\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:34317))

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.EntityTool[--]
       |--- #568 ui.EntityInstanceEditor
       |--- #569 tool.ResizeTool[--]
       |--- #570 display.EntityRender
       |--- #571 display.EntityRender
       |--- #572 display.EntityRender
       |--- #573 display.EntityRender
       |--- #574 display.EntityRender
       |--- #575 display.EntityRender
       |--- #576 display.EntityRender
       |--- #577 display.EntityRender
       |--- #578 display.EntityRender
       |--- #579 display.EntityRender
       |--- #580 display.EntityRender
       |--- #581 display.EntityRender
       |--- #582 display.EntityRender
       |--- #583 display.EntityRender
       |--- #584 display.EntityRender
       |--- #585 display.EntityRender
       |--- #586 display.EntityRender
       |--- #587 display.EntityRender
       |--- #588 display.EntityRender
       |--- #589 display.EntityRender
       |--- #590 display.EntityRender
       |--- #591 display.EntityRender
       |--- #592 display.EntityRender
       |--- #593 display.EntityRender
       |--- #594 tool.PickPoint[--]
 |--- #595 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by raulboo** [comment]
Got this exact same error in the same situation :(

**Comment by deepnight** [comment]
Yes that's a bug fixed in 0.8.2: right now, "single point" fields have a bug :(

**Comment by SolarLune** [comment]
I've also gotten this, but I'm glad to hear it's fixed!

**Comment by deepnight** [comment]
Closing (already fixed)
