### ISSUE TITLE
Crash During Export

### ISSUE THREAD

**Issue by drkylec** [deepnight/ldtk#527]
Note: This Happens during any exporting be it a PNG or TMX. Does it to any map I make and any folder I save to.

Stack:
```
LDtk version: 0.9.3-64bits
EPERM: operation not permitted, open 'C:/Users/Kyle/Desktop/K2Z_Games/LDTK/TestMap/png/0000-Level_0--00-GrassIntGrid.png'
Error
Error: EPERM: operation not permitted, open 'C:/Users/Kyle/Desktop/K2Z_Games/LDTK/TestMap/png/0000-Level_0--00-GrassIntGrid.png'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1283:35)
    at Function.dn_js_NodeTools.writeFileBytes (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:61403:13)
    at dn__$Delayer_Task.ops.push.cb (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:179190:27)
    at dn_Delayer.update (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:48145:20)
    at Function.dn_Process._doPreUpdate (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:111:12)
    at Function.dn_Process.updateAll (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:720:20)
    at Boot.update (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:4050:14)
    at Boot.mainLoop (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:4012:8)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #50 tool.lt.IntGridTool[--]
       |--- #75 ui.modal.panel.EditProject
       |--- #86 ui.ProjectSaving
       |--- #87 ui.modal.Progress
             |--- #88 dn.Process
```

Log:
```
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[WARNING]      Last chance for: Layer GrassIntGrid_baked deleted
[TIDY]         Removed lost layer instance in data.Level.Level_0(#0)
[EVENT]        LayerInstanceSelected
[EVENT]        LayerDefRemoved
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level_0(#0)
[RENDER]       Rendered level UI
[FILE]         Reading HTML template editProject from cache
[SAVE]         [TestMap] Preparing project saving...
[SAVE]         [TestMap] => PreChecks...
[SAVE]         [TestMap] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [TestMap] => AutoLayers...
[SAVE]         [TestMap] => SavingMainFile...
[SAVE]         [TestMap]   Preparing SavingData...
[SAVE]         [TestMap]   Writing C:/Users/Kyle/Desktop/K2Z_Games/LDTK/TestMap.ldtk...
[FILE]         Emptying dir C:/Users/Kyle/Desktop/K2Z_Games/LDTK/TestMap (onlyExts=[ldtkl])...
[SAVE]         [TestMap] => Done...
[SAVE]         [TestMap] Saving complete (TestMap.ldtk)
[FILE]         Saved "TestMap.ldtk".
[EVENT]        ProjectSaved
[EVENT]        ProjectSettingsChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level_0(#0)
[RENDER]       Rendered level UI
[SAVE]         [TestMap] Preparing project saving...
[SAVE]         [TestMap] => PreChecks...
[SAVE]         [TestMap] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [TestMap] => AutoLayers...
[SAVE]         [TestMap] => SavingMainFile...
[SAVE]         [TestMap]   Preparing SavingData...
[SAVE]         [TestMap]   Writing C:/Users/Kyle/Desktop/K2Z_Games/LDTK/TestMap.ldtk...
[FILE]         Emptying dir C:/Users/Kyle/Desktop/K2Z_Games/LDTK/TestMap (onlyExts=[ldtkl])...
[SAVE]         [TestMap] => SavingLayerImages...
[GENERAL]      "PNG export", 1 operation(s):
[SAVE]         [TestMap] Level Level_0...
[SAVE]         [TestMap]    -> Layer GrassIntGrid...
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        EPERM: operation not permitted, open 'C:/Users/Kyle/Desktop/K2Z_Games/LDTK/TestMap/png/0000-Level_0--00-GrassIntGrid.png' (Error)
[ERROR]        Error: EPERM: operation not permitted, open 'C:/Users/Kyle/Desktop/K2Z_Games/LDTK/TestMap/png/0000-Level_0--00-GrassIntGrid.png'
    at Object.openSync (fs.js:462:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1283:35)
    at Function.dn_js_NodeTools.writeFileBytes (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:61403:13)
    at dn__$Delayer_Task.ops.push.cb (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:179190:27)
    at dn_Delayer.update (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:48145:20)
    at Function.dn_Process._doPreUpdate (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:111:12)
    at Function.dn_Process.updateAll (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:720:20)
    at Boot.update (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:4050:14)
    at Boot.mainLoop (file:///C:/Users/Kyle/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:4012:8)

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #50 tool.lt.IntGridTool[--]
       |--- #75 ui.modal.panel.EditProject
       |--- #86 ui.ProjectSaving
       |--- #87 ui.modal.Progress
             |--- #88 dn.Process
 |--- #89 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
This should be fixed in 0.10.0
