### ISSUE TITLE
Cannot read property 'h' of null (TypeError)

### ISSUE THREAD

**Issue by dontpanic5** [deepnight/ldtk#535]
Got an error, stack dump below!

Stack:
```
LDtk version: 0.9.3-64bits
Cannot read property 'h' of null
TypeError
TypeError: Cannot read property 'h' of null
    at data_inst_LayerInstance.applyAutoLayerRuleToAllLayer (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:31845:30)
    at display_LevelRender.onGlobalEvent (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:36008:7)
    at misc_GlobalEventDispatcher.emit (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:149976:4)
    at ui_modal_panel_EditAllAutoLayerRules.onCreateRule (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:183959:21)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:184279:11)
    at HTMLButtonElement.dispatch (C:\Users\Nate\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:36324)
    at HTMLButtonElement.v.handle (C:\Users\Nate\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:34317)
```
Processes:
```
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 display.WorldRender
       |--- #5 display.LevelRender
       |--- #6 display.Camera
       |--- #7 display.Rulers[--]
       |--- #8 tool.SelectionTool[--]
       |--- #9 tool.lt.DoNothing[--]
       |--- #10 WorldTool
       |--- #11 tool.PanView[--]
       |--- #37 tool.lt.IntGridTool[--]
       |--- #39 ui.modal.panel.EditAllAutoLayerRules
       |--- #44 ui.Tip
```

Log:
```
[GENERAL]      "Initializing pixel data cache for "Minifantasy_DungeonWallTiles.png"", 14 operation(s):
[GENERAL]      Done "Initializing pixel data cache for "Minifantasy_DungeonWallTiles.png"" (0.09s)
[EVENT]        TilesetDefPixelDataCacheRebuilt 23
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level_0(#0)
[FILE]         Loading HTML template editLayerDefs
[TIDY]         Added missing layer instance IntGrid in data.Level.Level_0(#0)
[EVENT]        LayerInstanceSelected
[EVENT]        LayerDefAdded
[WARNING]      Full render requested
[RENDER]       Rendered level UI
[EVENT]        LayerDefChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level_0(#0)
[WARNING]      Full render requested
[FILE]         Loading HTML template colorPicker
[EVENT]        LayerDefChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level_0(#0)
[WARNING]      Full render requested
[EVENT]        AutoLayerRenderingChanged
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[FILE]         Reading HTML template colorPicker from cache
[EVENT]        LayerDefChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level_0(#0)
[WARNING]      Full render requested
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[EVENT]        LayerDefChanged
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level_0(#0)
[ERROR]        missing autoTilesCache in Instance[#24,Walls:IntGrid]
[WARNING]      Full render requested
[FILE]         Loading HTML template editAllAutoLayerRules
[GENERAL]      Added rule group
[EVENT]        LayerRuleGroupAdded
[GENERAL]      Added rule
[EVENT]        LayerRuleAdded 26
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'h' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'h' of null
    at data_inst_LayerInstance.applyAutoLayerRuleToAllLayer (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:31845:30)
    at display_LevelRender.onGlobalEvent (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:36008:7)
    at misc_GlobalEventDispatcher.emit (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:149976:4)
    at ui_modal_panel_EditAllAutoLayerRules.onCreateRule (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:183959:21)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/Nate/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:184279:11)
    at HTMLButtonElement.dispatch (C:\Users\Nate\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:36324)
    at HTMLButtonElement.v.handle (C:\Users\Nate\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:34317)

[GENERAL]      
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 display.WorldRender
       |--- #5 display.LevelRender
       |--- #6 display.Camera
       |--- #7 display.Rulers[--]
       |--- #8 tool.SelectionTool[--]
       |--- #9 tool.lt.DoNothing[--]
       |--- #10 WorldTool
       |--- #11 tool.PanView[--]
       |--- #37 tool.lt.IntGridTool[--]
       |--- #39 ui.modal.panel.EditAllAutoLayerRules
       |--- #44 ui.Tip
 |--- #45 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Needs to be checked again with 0.10.0
