### ISSUE TITLE
Crash when deleting all levels

### ISSUE THREAD

**Issue by realBoubli** [deepnight/ldtk#538]
LDtk crash when you delete all the levels, I don't even know why I've tested this.
Stack:
```
LDtk version: 0.9.3-64bits
Cannot read property 'uid' of null
TypeError
TypeError: Cannot read property 'uid' of null
    at page_Editor.selectLevel (file:///C:/Users/Boubli/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:155808:23)
    at Object.cb (file:///C:/Users/Boubli/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12861:21)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/Boubli/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:181496:6)
    at HTMLButtonElement.dispatch (C:\Users\Boubli\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:36324)
    at HTMLButtonElement.v.handle (C:\Users\Boubli\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:34317)
```
Processes:
```
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender [PAUSED]
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #29 ui.modal.panel.WorldPanel
       |--- #31 ui.modal.ContextMenu
       |--- #32 ui.LastChance
```

Log:
```

[BOOT]         App started
[BOOT]         Version: 0.9.3-64bits
[BOOT]         ExePath: C:/Users/Boubli/AppData/Local/Programs/ldtk
[BOOT]         Resources: C:\Users\Boubli\AppData\Local\Programs\ldtk\resources\app.asar
[BOOT]         SamplesPath: C:/Users/Boubli/AppData/Local/Programs/ldtk/samples
[BOOT]         Display: 1920x1080
[BOOT]         Args: soloValues=[], args=[]
[FILE]         Loading settings from C:/Users/Boubli/AppData/Roaming/LDtk/settings...
[BOOT]         AppZoomFactor: 1.0546875
[BOOT]         Calling appReady...
[NETWORK]      Looking for update
[BOOT]         Start args: path=null levelIndex=null
[BOOT]         Loading Home...
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from C:/Users/Boubli/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/home.html
[SAVE]         [sx] Preparing project saving...
[SAVE]         [sx] => PreChecks...
[SAVE]         [sx] => SavingMainFile...
[SAVE]         [sx]   Preparing SavingData...
[SAVE]         [sx]   Writing C:\Users\Boubli\Documents\GitHub\Proto-Engine\Proto Engine\Content\maps\sx.ldtk...
[SAVE]         [sx] => Done...
[SAVE]         [sx] Saving complete (sx.ldtk)
[GENERAL]      Page started: page.Editor()
[FILE]         Loading page template: editor from C:/Users/Boubli/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/editor.html
[FILE]         Cleared all file watches
[EVENT]        ProjectSelected
[RENDER]       Reset world render
[RENDER]       Rendered world level data.Level.Level_0(#0)
[FILE]         Loading HTML template editLayerDefs
[FILE]         Loading HTML template editProject
[FILE]         Loading HTML template worldPanel
[RENDER]       Rendered world level data.Level.Level_0(#0)
[EVENT]        LevelSelected 0
[RENDER]       Rendered world level data.Level.Level_0(#0)
[WARNING]      Last chance for: Level Level_0 removed
[EVENT]        LevelRemoved 0
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Boubli/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'uid' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'uid' of null
    at page_Editor.selectLevel (file:///C:/Users/Boubli/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:155808:23)
    at Object.cb (file:///C:/Users/Boubli/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12861:21)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/Boubli/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:181496:6)
    at HTMLButtonElement.dispatch (C:\Users\Boubli\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:36324)
    at HTMLButtonElement.v.handle (C:\Users\Boubli\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:34317)

[GENERAL]      
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender [PAUSED]
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #29 ui.modal.panel.WorldPanel
       |--- #31 ui.modal.ContextMenu
       |--- #32 ui.LastChance
 |--- #33 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Fixed, see #501
