### ISSUE TITLE
Moved an entity that had an Point (non array)

### ISSUE THREAD

**Issue by shmellyorc** [deepnight/ldtk#539]
"Cannot read property 'cx' of null (TypeError)"

Stack:
```
LDtk version: 0.9.3-64bits
Cannot read property 'cx' of null
TypeError
TypeError: Cannot read property 'cx' of null
    at GenericLevelElementGroup.moveSelecteds (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:7955:7)
    at tool_SelectionTool.useAt (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165658:36)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:11529:22)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165565:28)
    at page_Editor.onMouseUp (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153623:23)
    at page_Editor.onHeapsEvent (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153530:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:75873:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115715:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115545:9)
    at hxd_SceneEvents.checkEvents (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115631:10)
```
Processes:
```
#0 App
 |--- #1779 page.Editor
       |--- #1780 misc.FileWatcher
       |--- #1781 display.WorldRender
       |--- #1782 display.LevelRender
       |--- #1783 display.Camera
       |--- #1784 display.Rulers[--]
       |--- #1785 tool.SelectionTool[Add] [RUNNING]
       |--- #1786 tool.lt.DoNothing[--]
       |--- #1787 WorldTool
       |--- #1788 tool.PanView[--]
       |--- #1789 tool.lt.EntityTool[--]
       |--- #1796 tool.lt.TileTool [PAUSED][--]
       |--- #1800 tool.lt.TileTool [PAUSED][--]
       |--- #1846 tool.lt.IntGridTool [PAUSED][--]
       |--- #4547 ui.EntityInstanceEditor
       |--- #4548 tool.ResizeTool[--]
       |--- #4559 display.EntityRender
       |--- #4560 display.EntityRender
       |--- #4561 display.EntityRender
       |--- #4562 display.EntityRender
       |--- #4563 display.EntityRender
 |--- #4564 page.CrashReport
 |--- #4565 page.CrashReport
```

Log:
```
[EVENT]        LevelSelected 149
[RENDER]       Rendered world level data.Level.TheApprentice(#148)
[WARNING]      Full render requested
[RENDER]       Rendered world level data.Level.TheApprenticeHouse(#149)
[EVENT]        EntityInstanceAdded 22
[FILE]         Reading HTML template editLayerDefs from cache
[FILE]         Reading HTML template levelInstancePanel from cache
[EVENT]        FieldInstanceChanged 42
[FILE]         Reading HTML template worldPanel from cache
[RENDER]       Rendered world level data.Level.TheApprenticeHouse(#149)
[EVENT]        LevelSelected 149
[RENDER]       Rendered world level data.Level.TheApprenticeHouse(#149)
[WARNING]      Full render requested
[EVENT]        FieldInstanceChanged 44
[FILE]         Reading HTML template worldPanel from cache
[RENDER]       Rendered world level data.Level.TheApprenticeHouse(#149)
[EVENT]        LevelSelected 175
[RENDER]       Rendered world level data.Level.TheApprenticeHouse(#149)
[RENDER]       Rendered world level data.Level.ThePizzamon(#175)
[EVENT]        LevelSelected 175
[RENDER]       Rendered world level data.Level.ThePizzamon(#175)
[WARNING]      Full render requested
[EVENT]        EntityInstanceAdded 22
[EVENT]        FieldInstanceChanged 177
[EVENT]        FieldInstanceChanged 42
[EVENT]        EntityInstanceChanged 22
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'cx' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'cx' of null
    at GenericLevelElementGroup.moveSelecteds (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:7955:7)
    at tool_SelectionTool.useAt (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165658:36)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:11529:22)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165565:28)
    at page_Editor.onMouseUp (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153623:23)
    at HTMLBodyElement.<anonymous> (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:151628:10)
    at HTMLBodyElement.dispatch (C:\Users\Shmellyorc\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:36324)
    at HTMLBodyElement.v.handle (C:\Users\Shmellyorc\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:34317)

[GENERAL]      
#0 App
 |--- #1779 page.Editor
       |--- #1780 misc.FileWatcher
       |--- #1781 display.WorldRender
       |--- #1782 display.LevelRender
       |--- #1783 display.Camera
       |--- #1784 display.Rulers[--]
       |--- #1785 tool.SelectionTool[Add] [RUNNING]
       |--- #1786 tool.lt.DoNothing[--]
       |--- #1787 WorldTool
       |--- #1788 tool.PanView[--]
       |--- #1789 tool.lt.EntityTool[--]
       |--- #1796 tool.lt.TileTool [PAUSED][--]
       |--- #1800 tool.lt.TileTool [PAUSED][--]
       |--- #1846 tool.lt.IntGridTool [PAUSED][--]
       |--- #4547 ui.EntityInstanceEditor
       |--- #4548 tool.ResizeTool[--]
       |--- #4559 display.EntityRender
       |--- #4560 display.EntityRender
       |--- #4561 display.EntityRender
       |--- #4562 display.EntityRender
       |--- #4563 display.EntityRender
 |--- #4564 page.CrashReport

[EVENT]        EntityInstanceChanged 22
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'cx' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'cx' of null
    at GenericLevelElementGroup.moveSelecteds (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:7955:7)
    at tool_SelectionTool.useAt (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165658:36)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:11529:22)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165565:28)
    at page_Editor.onMouseUp (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153623:23)
    at page_Editor.onHeapsEvent (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153514:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:75873:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115715:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115545:9)
    at hxd_SceneEvents.checkEvents (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115631:10)

[GENERAL]      
#0 App
 |--- #1779 page.Editor
       |--- #1780 misc.FileWatcher
       |--- #1781 display.WorldRender
       |--- #1782 display.LevelRender
       |--- #1783 display.Camera
       |--- #1784 display.Rulers[--]
       |--- #1785 tool.SelectionTool[Add] [RUNNING]
       |--- #1786 tool.lt.DoNothing[--]
       |--- #1787 WorldTool
       |--- #1788 tool.PanView[--]
       |--- #1789 tool.lt.EntityTool[--]
       |--- #1796 tool.lt.TileTool [PAUSED][--]
       |--- #1800 tool.lt.TileTool [PAUSED][--]
       |--- #1846 tool.lt.IntGridTool [PAUSED][--]
       |--- #4547 ui.EntityInstanceEditor
       |--- #4548 tool.ResizeTool[--]
       |--- #4559 display.EntityRender
       |--- #4560 display.EntityRender
       |--- #4561 display.EntityRender
       |--- #4562 display.EntityRender
       |--- #4563 display.EntityRender
 |--- #4564 page.CrashReport
 |--- #4565 page.CrashReport

[EVENT]        EntityInstanceChanged 22
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'cx' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'cx' of null
    at GenericLevelElementGroup.moveSelecteds (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:7955:7)
    at tool_SelectionTool.useAt (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165658:36)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:11529:22)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165565:28)
    at page_Editor.onMouseUp (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153623:23)
    at page_Editor.onHeapsEvent (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153530:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:75873:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115715:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115545:9)
    at hxd_SceneEvents.checkEvents (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115631:10)

[GENERAL]      
#0 App
 |--- #1779 page.Editor
       |--- #1780 misc.FileWatcher
       |--- #1781 display.WorldRender
       |--- #1782 display.LevelRender
       |--- #1783 display.Camera
       |--- #1784 display.Rulers[--]
       |--- #1785 tool.SelectionTool[Add] [RUNNING]
       |--- #1786 tool.lt.DoNothing[--]
       |--- #1787 WorldTool
       |--- #1788 tool.PanView[--]
       |--- #1789 tool.lt.EntityTool[--]
       |--- #1796 tool.lt.TileTool [PAUSED][--]
       |--- #1800 tool.lt.TileTool [PAUSED][--]
       |--- #1846 tool.lt.IntGridTool [PAUSED][--]
       |--- #4547 ui.EntityInstanceEditor
       |--- #4548 tool.ResizeTool[--]
       |--- #4559 display.EntityRender
       |--- #4560 display.EntityRender
       |--- #4561 display.EntityRender
       |--- #4562 display.EntityRender
       |--- #4563 display.EntityRender
 |--- #4564 page.CrashReport
 |--- #4565 page.CrashReport
 |--- #4566 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Hi! Sorry about this one, it actually happened to me today too 🤔  I'll fix in next update.
