### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by bolon667** [deepnight/ldtk#540]
Stack:
```
LDtk version: 0.9.3-64bits
Cannot read property 'cx' of null
TypeError
TypeError: Cannot read property 'cx' of null
    at GenericLevelElementGroup.moveSelecteds (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:7955:7)
    at tool_SelectionTool.useAt (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165658:36)
    at tool_SelectionTool.stopUsing (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:11529:22)
    at tool_SelectionTool.stopUsing (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165565:28)
    at page_Editor.onMouseUp (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153623:23)
    at page_Editor.onHeapsEvent (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153530:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:75873:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115715:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115545:9)
    at hxd_SceneEvents.checkEvents (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115631:10)
```
Processes:
```
#0 App
 |--- #1 page.Editor
       |--- #2 misc.FileWatcher
       |--- #3 display.WorldRender
       |--- #4 display.LevelRender
       |--- #5 display.Camera
       |--- #6 display.Rulers[--]
       |--- #7 tool.SelectionTool[Add] [RUNNING]
       |--- #8 tool.lt.DoNothing[--]
       |--- #9 WorldTool
       |--- #10 tool.PanView[--]
       |--- #11 tool.lt.DoNothing [PAUSED][--]
       |--- #57 tool.lt.EntityTool[--]
       |--- #61 tool.lt.IntGridTool [PAUSED][--]
       |--- #62 tool.lt.TileTool [PAUSED][--]
       |--- #350 ui.EntityInstanceEditor
       |--- #351 tool.ResizeTool[--]
       |--- #352 display.EntityRender
       |--- #353 display.EntityRender
       |--- #354 display.EntityRender
 |--- #355 page.CrashReport
 |--- #356 page.CrashReport
```

Log:
```
[SAVE]         [GameWorld2]   Preparing SavingData...
[SAVE]         [GameWorld2]   Writing D:\Codding\Sega\Under-Prog Games\shootEmUp\GameWorld2.ldtk...
[FILE]         Emptying dir D:\Codding\Sega\Under-Prog Games\shootEmUp\GameWorld2 (onlyExts=[ldtkl])...
[SAVE]         [GameWorld2] => SavingLayerImages...
[FILE]         Emptying dir D:\Codding\Sega\Under-Prog Games\shootEmUp\GameWorld2/png (onlyExts=[png])...
[GENERAL]      "PNG export", 2 operation(s):
[SAVE]         [GameWorld2] Level Level_1...
[SAVE]         [GameWorld2]    -> Layer AutoLayer_bga...
[SAVE]         [GameWorld2]    -> Layer Entities...
[SAVE]         [GameWorld2]    -> Layer Coll...
[SAVE]         [GameWorld2]    -> Layer Tiles_bgb...
[SAVE]         [GameWorld2] Level Level_2...
[SAVE]         [GameWorld2]    -> Layer AutoLayer_bga...
[SAVE]         [GameWorld2]    -> Layer Entities...
[SAVE]         [GameWorld2]    -> Layer Coll...
[SAVE]         [GameWorld2]    -> Layer Tiles_bgb...
[GENERAL]      Done "PNG export" (1.12s)
[SAVE]         [GameWorld2]   Saved 6 PNG(s)...
[SAVE]         [GameWorld2] => Done...
[SAVE]         [GameWorld2] Saving complete (GameWorld2.ldtk)
[FILE]         Saved "GameWorld2.ldtk".
[EVENT]        ProjectSaved
[EVENT]        FieldInstanceChanged 103
[EVENT]        EntityInstanceRemoved 102
[EVENT]        EntityInstanceAdded 118
[EVENT]        EntityInstanceChanged 118
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'cx' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'cx' of null
    at GenericLevelElementGroup.moveSelecteds (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:7955:7)
    at tool_SelectionTool.useAt (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165658:36)
    at tool_SelectionTool.stopUsing (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:11529:22)
    at tool_SelectionTool.stopUsing (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165565:28)
    at page_Editor.onMouseUp (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153623:23)
    at HTMLBodyElement.<anonymous> (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:151628:10)
    at HTMLBodyElement.dispatch (C:\Users\user\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:36324)
    at HTMLBodyElement.v.handle (C:\Users\user\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery-git.min.js:2:34317)

[GENERAL]      
#0 App
 |--- #1 page.Editor
       |--- #2 misc.FileWatcher
       |--- #3 display.WorldRender
       |--- #4 display.LevelRender
       |--- #5 display.Camera
       |--- #6 display.Rulers[--]
       |--- #7 tool.SelectionTool[Add] [RUNNING]
       |--- #8 tool.lt.DoNothing[--]
       |--- #9 WorldTool
       |--- #10 tool.PanView[--]
       |--- #11 tool.lt.DoNothing [PAUSED][--]
       |--- #57 tool.lt.EntityTool[--]
       |--- #61 tool.lt.IntGridTool [PAUSED][--]
       |--- #62 tool.lt.TileTool [PAUSED][--]
       |--- #350 ui.EntityInstanceEditor
       |--- #351 tool.ResizeTool[--]
       |--- #352 display.EntityRender
       |--- #353 display.EntityRender
       |--- #354 display.EntityRender
 |--- #355 page.CrashReport

[EVENT]        EntityInstanceChanged 118
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'cx' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'cx' of null
    at GenericLevelElementGroup.moveSelecteds (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:7955:7)
    at tool_SelectionTool.useAt (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165658:36)
    at tool_SelectionTool.stopUsing (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:11529:22)
    at tool_SelectionTool.stopUsing (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165565:28)
    at page_Editor.onMouseUp (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153623:23)
    at page_Editor.onHeapsEvent (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153514:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:75873:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115715:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115545:9)
    at hxd_SceneEvents.checkEvents (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115631:10)

[GENERAL]      
#0 App
 |--- #1 page.Editor
       |--- #2 misc.FileWatcher
       |--- #3 display.WorldRender
       |--- #4 display.LevelRender
       |--- #5 display.Camera
       |--- #6 display.Rulers[--]
       |--- #7 tool.SelectionTool[Add] [RUNNING]
       |--- #8 tool.lt.DoNothing[--]
       |--- #9 WorldTool
       |--- #10 tool.PanView[--]
       |--- #11 tool.lt.DoNothing [PAUSED][--]
       |--- #57 tool.lt.EntityTool[--]
       |--- #61 tool.lt.IntGridTool [PAUSED][--]
       |--- #62 tool.lt.TileTool [PAUSED][--]
       |--- #350 ui.EntityInstanceEditor
       |--- #351 tool.ResizeTool[--]
       |--- #352 display.EntityRender
       |--- #353 display.EntityRender
       |--- #354 display.EntityRender
 |--- #355 page.CrashReport
 |--- #356 page.CrashReport

[EVENT]        EntityInstanceChanged 118
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read property 'cx' of null (TypeError)
[ERROR]        TypeError: Cannot read property 'cx' of null
    at GenericLevelElementGroup.moveSelecteds (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:7955:7)
    at tool_SelectionTool.useAt (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165658:36)
    at tool_SelectionTool.stopUsing (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:11529:22)
    at tool_SelectionTool.stopUsing (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165565:28)
    at page_Editor.onMouseUp (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153623:23)
    at page_Editor.onHeapsEvent (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153530:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:75873:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115715:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115545:9)
    at hxd_SceneEvents.checkEvents (file:///C:/Users/user/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115631:10)

[GENERAL]      
#0 App
 |--- #1 page.Editor
       |--- #2 misc.FileWatcher
       |--- #3 display.WorldRender
       |--- #4 display.LevelRender
       |--- #5 display.Camera
       |--- #6 display.Rulers[--]
       |--- #7 tool.SelectionTool[Add] [RUNNING]
       |--- #8 tool.lt.DoNothing[--]
       |--- #9 WorldTool
       |--- #10 tool.PanView[--]
       |--- #11 tool.lt.DoNothing [PAUSED][--]
       |--- #57 tool.lt.EntityTool[--]
       |--- #61 tool.lt.IntGridTool [PAUSED][--]
       |--- #62 tool.lt.TileTool [PAUSED][--]
       |--- #350 ui.EntityInstanceEditor
       |--- #351 tool.ResizeTool[--]
       |--- #352 display.EntityRender
       |--- #353 display.EntityRender
       |--- #354 display.EntityRender
 |--- #355 page.CrashReport
 |--- #356 page.CrashReport
 |--- #357 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Thanks for reporting: it's related to #539 
It should be fixed in next update. 

(closing duplicate issue)
