### ISSUE TITLE
Placing objects on top of each other sometimes causes crash

### ISSUE THREAD

**Issue by wy477wh173** [deepnight/ldtk#560]
Stack:
```
LDtk version: 0.9.3-64bits
Cannot read property 'cx' of null
TypeError
TypeError: Cannot read property 'cx' of null
    at GenericLevelElementGroup.moveSelecteds (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:7955:7)
    at tool_SelectionTool.useAt (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165658:36)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:11529:22)
    at tool_SelectionTool.stopUsing (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165565:28)
    at page_Editor.onMouseUp (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153623:23)
    at page_Editor.onHeapsEvent (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:153530:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:75873:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115715:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115545:9)
    at hxd_SceneEvents.checkEvents (file:///C:/Users/Wyatt/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:115631:10)
```
Processes:
```
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 display.WorldRender
       |--- #5 display.LevelRender
       |--- #6 display.Camera
       |--- #7 display.Rulers[--]
       |--- #8 tool.SelectionTool[Add] [RUNNING]
       |--- #9 tool.lt.DoNothing[--]
       |--- #10 WorldTool
       |--- #11 tool.PanView[--]
       |--- #12 tool.lt.TileTool [PAUSED][--]
       |--- #566 tool.lt.TileTool [PAUSED][--]
       |--- #567 tool.lt.EntityTool[--]
       |--- #5776 ui.EntityInstanceEditor
       |--- #5777 tool.ResizeTool[--]
       |--- #5778 display.EntityRender
       |--- #5779 display.EntityRender
       |--- #5780 display.EntityRender
       |--- #5781 display.EntityRender
       |--- #5782 display.EntityRender
       |--- #5783 display.EntityRender
       |--- #5784 display.EntityRender
       |--- #5785 display.EntityRender
       |--- #5786 display.EntityRender
       |--- #5787 display.EntityRender
       |--- #5788 display.EntityRender
       |--- #5789 display.EntityRender
       |--- #5790 display.EntityRender
       |--- #5791 display.EntityRender
       |--- #5792 display.EntityRender
       |--- #5793 display.EntityRender
       |--- #5794 display.EntityRender
       |--- #5795 display.EntityRender
       |--- #5796 display.EntityRender
       |--- #5797 display.EntityRender
       |--- #5798 display.EntityRender
       |--- #5799 display.EntityRender
       |--- #5800 display.EntityRender
       |--- #5801 display.EntityRender
       |--- #5802 display.EntityRender
       |--- #5803 display.EntityRender
       |--- #5804 display.EntityRender
       |--- #5805 display.EntityRender
       |--- #5806 display.EntityRender
       |--- #5807 display.EntityRender
       |--- #5808 display.EntityRender
       |--- #5809 display.EntityRender
       |--- #5810 display.EntityRender
       |--- #5811 display.EntityRender
       |--- #5812 display.EntityRender
       |--- #5813 display.EntityRender
       |--- #5814 display.EntityRender
       |--- #5815 display.EntityRender
       |--- #5816 display.EntityRender
       |--- #5817 display.EntityRender
       |--- #5818 display.EntityRender
       |--- #5819 display.EntityRender
       |--- #5820 display.EntityRender
       |--- #5821 display.EntityRender
       |--- #5822 display.EntityRender
       |--- #5823 display.EntityRender
       |--- #5824 display.EntityRender
       |--- #5825 display.EntityRender
       |--- #5826 display.EntityRender
       |--- #5827 display.EntityRender
       |--- #5828 display.EntityRender
       |--- #5829 display.EntityRender
       |--- #5830 display.EntityRender
       |--- #5831 display.EntityRender
       |--- #5832 display.EntityRender
       |--- #5833 display.EntityRender
       |--- #5834 display.EntityRender
       |--- #5835 display.EntityRender
       |--- #5836 display.EntityRender
       |--- #5837 display.EntityRender
       |--- #5838 display.EntityRender
       |--- #5839 display.EntityRender
       |--- #5840 display.EntityRender
       |--- #5841 display.EntityRender
       |--- #5842 display.EntityRender
       |--- #5843 display.EntityRender
       |--- #5844 display.EntityRender
       |--- #5845 display.EntityRender
       |--- #5846 display.EntityRender
       |--- #5847 display.EntityRender
       |--- #5848 display.EntityRender
       |--- #5849 display.EntityRender
       |--- #5850 display.EntityRender
       |--- #5851 display.EntityRender
       |--- #5852 display.EntityRender
       |--- #5853 display.EntityRender
       |--- #5854 display.EntityRender
       |--- #5855 display.EntityRender
       |--- #5856 display.EntityRender
       |--- #5857 display.EntityRender
       |--- #5858 display.EntityRender
       |--- #5859 display.EntityRender
       |--- #5860 display.EntityRender
       |--- #5861 display.EntityRender
       |--- #5862 display.EntityRender
       |--- #5863 display.EntityRender
       |--- #5864 display.EntityRender
       |--- #5865 display.EntityRender
       |--- #5866 display.EntityRender
       |--- #5867 display.EntityRender
       |--- #5868 display.EntityRender
       |--- #5869 display.EntityRender
       |--- #5870 display.EntityRender
       |--- #5871 display.EntityRender
       |--- #5872 display.EntityRender
       |--- #5873 display.EntityRender
       |--- #5874 display.EntityRender
       |--- #5875 display.EntityRender
       |--- #5876 display.EntityRender
       |--- #5877 display.EntityRender
       |--- #5878 display.EntityRender
       |--- #5879 display.EntityRender
       |--- #5880 display.EntityRender
       |--- #5881 display.EntityRender
       |--- #5882 display.EntityRender
       |--- #5883 display.EntityRender
       |--- #5884 display.EntityRender
       |--- #5885 display.EntityRender
 |--- #5886 page.CrashReport
 |--- #5887 page.CrashReport
```

Log:
```
[SAVE]         [zone0]   Preparing SavingData...
[SAVE]         [zone0]   Writing C:/Users/Wyatt/Documents/Dev/curry/Curry/curry_source/datafiles/Assets/lvl/zone0.ldtk...
[FILE]         Emptying dir C:/Users/Wyatt/Documents/Dev/curry/Curry/curry_source/datafiles/Assets/lvl/zone0 (onlyExts=[ldtkl])...
[SAVE]         [zone0] => Done...
[SAVE]         [zone0] Saving complete (zone0.ldtk)
[FILE]         Saved "zone0.ldtk".
[EVENT]        ProjectSaved
[EVENT]        EntityInstanceAdded 26
[EVENT]        EntityInstanceChanged 26
[EVENT]        FieldInstanceChanged 41
[EVENT]        EntityInstanceAdded 26
[EVENT]        EntityInstanceChanged 26
[EVENT]        EntityInstanceAdded 26
[EVENT]        EntityInstanceChanged 26
[EVENT]        EntityInstanceChanged 26
[EVENT]        EntityInstanceChanged 26
[SAVE]         [zone0] Preparing project saving...
[SAVE]         [zone0] => PreChecks...
[SAVE]         [zone0] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [zone0] => AutoLayers...
[SAVE]         [zone0] => SavingMainFile...
[SAVE]         [zone0]   Preparing SavingData...
[SAVE]         [zone0]   Writing C:/Users/Wyatt/Documents/Dev/curry/Curry/curry_source/datafiles/Assets/lvl/zone0.ldtk...
[FILE]         Emptying dir C:/Users/Wyatt/Documents/Dev/curry/Curry/curry_source/datafiles/Assets/lvl/zone0 (onlyExts=[ldtkl])...
[SAVE]         [zone0] => Done...
[SAVE]         [zone0] Saving complete (zone0.ldtk)
[FILE]         Saved "zone0.ldtk".
[EVENT]        ProjectSaved
[EVENT]        EntityInstanceChanged 48
[EVENT]        EntityInstanceChanged 48
[EVENT]        EntityInstanceChanged 48
[EVENT]        EntityInstanceChanged 48
[EVENT]        EntityInstanceAdded 48
[EVENT]        FieldInstanceChanged 49
[SAVE]         [zone0] Preparing project saving...
[SAVE]         [zone0] => PreChecks...
[SAVE]         [zone0] => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         [zone0] => AutoLayers...
[SAVE]         [zone0] => SavingMainFile...
[SAVE]         [zone0]   Preparing SavingData...
[SAVE]         [zone0]   Writing C:/Users/Wyatt/Documents/Dev/curry/Curry/curry_source/datafiles/Assets/lvl/zone0.ldtk...
[FILE]         Emptying dir C:/Users/Wyatt/Documents/Dev/curry/Curry/curry_source/datafiles/Assets/lvl/zone0 (onlyExts=[ldtkl])...
[SAVE]         [zone0] => Done...
[SAVE]         [zone0] Saving complete (zone0.ldtk)
[FILE]         Saved "zone0.ldtk".
[EVENT]        ProjectSaved
[EVENT]        EntityInstanceAdded 48
[EVENT]        FieldInstanceChanged 49
```

**Comment by deepnight** [comment]
I suppose it's related to an existing crash when you have a "Point" field in this entity and you try to move the entity. 

Is that the case?

**Comment by wy477wh173** [comment]
> 

It's possible. This entity has a point attached, but this specifically happens when the point hasn't yet been set and the entity is moved into a space with another entity (which also has a point, but has already been set)

**Comment by deepnight** [comment]
Thank you!
I think the presence of another entity is unrelated, it looks like the problem here is the "null" point value.
