### ISSUE TITLE
[CRASH] TypeError: Cannot read properties of null (reading 'layerJsons')

### ISSUE THREAD

**Issue by PoolloverNathan** [deepnight/ldtk#657]
Stack:
```
LDtk version: 1.1.0-64bits
Cannot read properties of null (reading 'layerJsons')
TypeError
TypeError: Cannot read properties of null (reading 'layerJsons')
    at LevelTimeline.prolongatePreviousStates (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12299:10)
    at LevelTimeline.saveLayerStates (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12246:8)
    at tool_SelectionTool.onKeyPress (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:194847:45)
    at page_Editor.onKeyPress (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:177611:25)
    at App.onKeyPress (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3482:24)
    at App.onHeapsKeyDown (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3348:8)
    at App.onHeapsEvent (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3306:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:94939:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:137439:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:137269:9)
```
Processes:
```
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 display.WorldRender
       |--- #5 display.LevelRender
       |--- #6 display.Camera
       |--- #7 display.Rulers[--]
       |--- #8 tool.SelectionTool[--]
       |--- #9 tool.lt.DoNothing[--]
       |--- #10 WorldTool
       |--- #11 tool.PanView[--]
       |--- #12 tool.lt.EntityTool [PAUSED][--]
       |--- #35 tool.lt.TileTool [PAUSED][--]
       |--- #36 tool.lt.TileTool[--]
```

Log:
```
[RENDER]       Rendering world bounds...
[EVENT]        LevelSelected 179
[RENDER]       Rendering world level fields data.Level.InnOutside(#166)...
[RENDER]       Rendering world level fields data.Level.Lake(#171)...
[RENDER]       Rendering world level data.Level._1(#179)...
[RENDER]       Rendering world level fields data.Level._1(#179)...
[RENDER]       Rendering world bg...
[EVENT]        LevelSelected 179
[RENDER]       Rendering world level data.Level._1(#179)...
[RENDER]       Rendering world level fields data.Level._1(#179)...
[WARNING]      Full level render requested
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LayerInstanceEditedByTool
[FILE]         Reading HTML template worldPanel from cache
[FILE]         Reading HTML template levelInstanceForm from cache
[RENDER]       Rendering world level data.Level._1(#179)...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level data.Level.Crypt_1(#169)...
[EVENT]        LevelSelected 179
[RENDER]       Rendering world level data.Level._1(#179)...
[RENDER]       Rendering world level fields data.Level._1(#179)...
[EVENT]        LevelResized 179
[EVENT]        LevelJsonCacheInvalidated
[RENDER]       Rendering world bounds...
[WARNING]      Full level render requested
[RENDER]       Rendering world level data.Level._1(#179)...
[RENDER]       Rendering world level fields data.Level._1(#179)...
[WARNING]      Full level render requested
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template worldPanel from cache
[FILE]         Reading HTML template levelInstanceForm from cache
[RENDER]       Rendering world level data.Level._1(#179)...
[RENDER]       Rendering world bg...
[EVENT]        LevelSelected 179
[RENDER]       Rendering world level data.Level._1(#179)...
[RENDER]       Rendering world level fields data.Level._1(#179)...
[WARNING]      Full level render requested
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'layerJsons') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'layerJsons')
    at LevelTimeline.prolongatePreviousStates (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12299:10)
    at LevelTimeline.saveLayerStates (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12246:8)
    at tool_SelectionTool.onKeyPress (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:194847:45)
    at page_Editor.onKeyPress (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:177611:25)
    at App.onKeyPress (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3482:24)
    at App.onHeapsKeyDown (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3348:8)
    at App.onHeapsEvent (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3306:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:94939:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:137439:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/Nathan/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:137269:9)

[GENERAL]      
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 display.WorldRender
       |--- #5 display.LevelRender
       |--- #6 display.Camera
       |--- #7 display.Rulers[--]
       |--- #8 tool.SelectionTool[--]
       |--- #9 tool.lt.DoNothing[--]
       |--- #10 WorldTool
       |--- #11 tool.PanView[--]
       |--- #12 tool.lt.EntityTool [PAUSED][--]
       |--- #35 tool.lt.TileTool [PAUSED][--]
       |--- #36 tool.lt.TileTool[--]
 |--- #87 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Added a check in 1.1.1, but this needs more testing to determine when `layersJson` could be null in `LevelTimeline`
