### ISSUE TITLE
Crash when duplicating level

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#666]
Occurred while duplicating the level in the `Entities` sample.
This appears to occur in levels then involve entity references. I've tried duplicating levels without entity references and they appear to duplicate correctly without a crash. But that's my guess.

Stack:
```
LDtk version: 1.1.1-64bits
Cannot read properties of null (reading '_li')
TypeError
TypeError: Cannot read properties of null (reading '_li')
    at data_World.duplicateLevel (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:26706:17)
    at Object.cb (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:17605:95)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:217996:6)
    at HTMLButtonElement.dispatch (C:\Users\cameo\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (C:\Users\cameo\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)
```
Processes:
```
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 display.WorldRender
       |--- #5 display.LevelRender [PAUSED]
       |--- #6 display.Camera
       |--- #7 display.Rulers[--]
       |--- #8 tool.SelectionTool[--]
       |--- #9 tool.lt.DoNothing[--]
       |--- #10 WorldTool
       |--- #11 tool.PanView[--]
       |--- #12 tool.lt.EntityTool[--]
       |--- #64 ui.modal.panel.WorldPanel
       |--- #65 ui.modal.ContextMenu
```

Log:
```
[CACHE]        Caching image atlas/Inca_front_by_Kronbits-extended.png...
[CACHE]         -> identified as Png
[CACHE]         -> base64 18368
[CACHE]         -> pixels 320x224
[FILE]          -> Loaded 13774 bytes.
[FILE]          -> Decoded 320x224 pixels.
[WARNING]      Tileset remapping...
[FILE]          -> Reload result: Ok
[FILE]          -> pixelData: Ok
[EVENT]        TilesetImageLoaded
[FILE]         Reloading tileset: Inca_back2_by_Kronbits path=atlas/Inca_back2_by_Kronbits.png
[FILE]         Loading atlas image: atlas/Inca_back2_by_Kronbits.png...
[CACHE]        Caching image atlas/Inca_back2_by_Kronbits.png...
[CACHE]         -> identified as Png
[CACHE]         -> base64 4472
[CACHE]         -> pixels 160x224
[FILE]          -> Loaded 3354 bytes.
[FILE]          -> Decoded 160x224 pixels.
[WARNING]      Tileset remapping...
[FILE]          -> Reload result: Ok
[FILE]          -> pixelData: Ok
[EVENT]        TilesetImageLoaded
[EVENT]        ProjectSelected
[RENDER]       Rendered level UI
[RENDER]       Rendering all world...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bounds...
[FILE]         Watching file: C:\Users\cameo\Documents\_Personal\UnityProjects\LDtkToUnity\Assets\Samples\Samples\atlas\TopDown_by_deepnight.png
[FILE]         Watching file: C:\Users\cameo\Documents\_Personal\UnityProjects\LDtkToUnity\Assets\Samples\Samples\atlas\Inca_front_by_Kronbits-extended.png
[FILE]         Watching file: C:\Users\cameo\Documents\_Personal\UnityProjects\LDtkToUnity\Assets\Samples\Samples\atlas\Inca_back2_by_Kronbits.png
[RENDER]       Rendering world level data.Level.Entities_demo(#0)...
[RENDER]       Rendering world level fields data.Level.Entities_demo(#0)...
[RENDER]       Rendering world bg...
[GENERAL]      Progress completed: "Entities.ldtk: Project..." (0.8s)
[FILE]         Loading HTML template worldPanel
[FILE]         Loading HTML template levelInstanceForm
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level data.Level.Entities_demo(#0)...
[EVENT]        LevelSelected 0
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level data.Level.Entities_demo(#0)...
[RENDER]       Rendering world level fields data.Level.Entities_demo(#0)...
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading '_li') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading '_li')
    at data_World.duplicateLevel (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:26706:17)
    at Object.cb (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:17605:95)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:217996:6)
    at HTMLButtonElement.dispatch (C:\Users\cameo\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (C:\Users\cameo\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)

[GENERAL]      
#0 App
 |--- #2 page.Editor
       |--- #3 misc.FileWatcher
       |--- #4 display.WorldRender
       |--- #5 display.LevelRender [PAUSED]
       |--- #6 display.Camera
       |--- #7 display.Rulers[--]
       |--- #8 tool.SelectionTool[--]
       |--- #9 tool.lt.DoNothing[--]
       |--- #10 WorldTool
       |--- #11 tool.PanView[--]
       |--- #12 tool.lt.EntityTool[--]
       |--- #64 ui.modal.panel.WorldPanel
       |--- #65 ui.modal.ContextMenu
 |--- #66 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
This will be fixed in 1.1.2
