### ISSUE TITLE
Cannot read properties of null (reading 'layerJsons')

### ISSUE THREAD

**Issue by abueide** [deepnight/ldtk#674]
Steps to reproduce:
open ldtk
new project
create new level
click new level
press del button on keyboard

Stack:
```
LDtk version: 1.1.1-64bits
Cannot read properties of null (reading 'layerJsons')
TypeError
TypeError: Cannot read properties of null (reading 'layerJsons')
    at LevelTimeline.prolongatePreviousStates (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12294:8)
    at LevelTimeline.saveLayerStates (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12246:8)
    at tool_SelectionTool.onKeyPress (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:195081:45)
    at page_Editor.onKeyPress (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:177821:25)
    at App.onKeyPress (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3482:24)
    at App.onHeapsKeyDown (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3348:8)
    at App.onHeapsEvent (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3306:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:95149:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:137649:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:137479:9)
```
Processes:
```
#0 App
 |--- #8 page.Editor
       |--- #9 misc.FileWatcher
       |--- #10 display.WorldRender
       |--- #11 display.LevelRender
       |--- #12 display.Camera
       |--- #13 display.Rulers[--]
       |--- #14 tool.SelectionTool[--]
       |--- #15 tool.lt.DoNothing[--]
       |--- #16 WorldTool
       |--- #17 tool.PanView[--]
```

Log:
```
[FILE]         Reading HTML template worldPanel from cache
[FILE]         Reading HTML template levelInstanceForm from cache
[RENDER]       Rendering world level data.Level.Level_0(#0)...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[EVENT]        LevelAdded 1
[RENDER]       Rendering world bounds...
[EVENT]        LevelSelected 1
[TIMELINE]     Garbage collected level: #0
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level data.Level.Level_0(#0)...
[RENDER]       Rendering world level fields data.Level.Level_1(#1)...
[RENDER]       Rendering world level data.Level.Level_1(#1)...
[EVENT]        LevelSelected 1
[RENDER]       Rendering world level data.Level.Level_1(#1)...
[RENDER]       Rendering world level fields data.Level.Level_1(#1)...
[WARNING]      Full level render requested
[EVENT]        LevelSelected 0
[TIMELINE]     Garbage collected level: #1
[RENDER]       Rendering world level data.Level.Level_0(#0)...
[RENDER]       Rendering world level fields data.Level.Level_0(#0)...
[WARNING]      Full level render requested
[RENDER]       Rendering world level data.Level.Level_1(#1)...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[EVENT]        LevelSelected 1
[TIMELINE]     Garbage collected level: #0
[WARNING]      Full level render requested
[RENDER]       Rendering world level data.Level.Level_0(#0)...
[RENDER]       Rendering world level fields data.Level.Level_1(#1)...
[RENDER]       Rendering world level data.Level.Level_1(#1)...
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'layerJsons') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'layerJsons')
    at LevelTimeline.prolongatePreviousStates (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12294:8)
    at LevelTimeline.saveLayerStates (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:12246:8)
    at tool_SelectionTool.onKeyPress (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:195081:45)
    at page_Editor.onKeyPress (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:177821:25)
    at App.onKeyPress (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3482:24)
    at App.onHeapsKeyDown (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3348:8)
    at App.onHeapsEvent (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:3306:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:95149:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:137649:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/andrea/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:137479:9)

[GENERAL]      
#0 App
 |--- #8 page.Editor
       |--- #9 misc.FileWatcher
       |--- #10 display.WorldRender
       |--- #11 display.LevelRender
       |--- #12 display.Camera
       |--- #13 display.Rulers[--]
       |--- #14 tool.SelectionTool[--]
       |--- #15 tool.lt.DoNothing[--]
       |--- #16 WorldTool
       |--- #17 tool.PanView[--]
 |--- #71 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by abueide** [comment]
sorry duplicate of https://github.com/deepnight/ldtk/issues/657
