### ISSUE TITLE
EBUSY: resource busy or locked, open ...

### ISSUE THREAD

**Issue by shmellyorc** [deepnight/ldtk#695]
Was editing the tilemap and got this error :(

Stack:
```
LDtk version: 1.1.3-64bits
EBUSY: resource busy or locked, open 'C:/Users/Shmellyorc/Documents/Pizzamon/Pizzamon/Content/Map/Pizzamon.ldtk'
Error
Error: EBUSY: resource busy or locked, open 'C:/Users/Shmellyorc/Documents/Pizzamon/Pizzamon/Content/Map/Pizzamon.ldtk'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.writeFileSync (node:fs:2153:35)
    at Function.dn_js_NodeTools.writeFileString (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:80121:13)
    at Object.cb (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:215697:21)
    at ui_modal_Progress.update (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:220409:8)
    at Function.dn_Process._doMainUpdate (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:223:4)
    at Function.dn_Process._doMainUpdate (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:266:15)
    at Function.dn_Process._doMainUpdate (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:266:15)
    at Function.dn_Process.updateAll (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:734:14)
```
Processes:
```
#0 App
 |--- #1874 page.Editor
       |--- #1875 misc.FileWatcher
       |--- #1876 display.WorldRender
       |--- #1877 display.LevelRender
       |--- #1878 display.Camera
       |--- #1879 display.Rulers[--]
       |--- #1880 tool.SelectionTool[--]
       |--- #1881 tool.lt.DoNothing[--]
       |--- #1882 WorldTool
       |--- #1883 tool.PanView[--]
       |--- #2019 tool.lt.IntGridTool [PAUSED][--]
       |--- #2022 tool.lt.TileTool [PAUSED][--]
       |--- #2024 tool.lt.TileTool[--]
       |--- #2029 tool.lt.IntGridTool [PAUSED][--]
       |--- #2486 tool.lt.EntityTool [PAUSED][--]
       |--- #3879 display.EntityRender
       |--- #3880 ui.ProjectSaver
       |--- #3881 ui.modal.MetaProgress
       |--- #3884 ui.modal.Progress
```

Log:
```
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[EVENT]        ToolValueSelected
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LevelJsonCacheInvalidated
[EVENT]        LayerInstanceEditedByTool
[RENDER]       Rendering world level fields data.Level.World_Level_215(#921)...
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LevelSelected 920
[RENDER]       Rendering world level data.Level.World_Level_214(#920)...
[RENDER]       Rendering world level fields data.Level.World_Level_214(#920)...
[WARNING]      Full level render requested
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level data.Level.World_Level_215(#921)...
[SAVE]         Preparing project saving: C:/Users/Shmellyorc/Documents/Pizzamon/Pizzamon/Content/Map/Pizzamon.ldtk...
[SAVE]         => PreChecks...
[SAVE]         => BeforeSavingActions...
[EVENT]        BeforeProjectSaving
[SAVE]         => AutoLayers...
[SAVE]         => Backup...
[SAVE]         Backing up C:/Users/Shmellyorc/Documents/Pizzamon/Pizzamon/Content/Map to C:/Users/Shmellyorc/Documents/Pizzamon/Pizzamon/Content/Map/Pizzamon/backups/backup_2022-05-25_17-28-15...
[SAVE]           Found 1 files.
[GENERAL]      Progress created.
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "Backup", 2 operation(s)
[SAVE]         Removing older backup: backup_2022-05-25_14-19-15
[GENERAL]      Progress completed: "Backup" (0s)
[SAVE]           Done!
[GENERAL]      Progress created.
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "Preparing levels...", 235 operation(s)
[GENERAL]      Progress completed: "Preparing levels..." (0s)
[SAVE]         => SavingMainFile...
[GENERAL]      Progress created.
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "Saving main file...", 2 operation(s)
[SAVE]           Preparing SavingData...
[SAVE]           Writing C:/Users/Shmellyorc/Documents/Pizzamon/Pizzamon/Content/Map/Pizzamon.ldtk...
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        EBUSY: resource busy or locked, open 'C:/Users/Shmellyorc/Documents/Pizzamon/Pizzamon/Content/Map/Pizzamon.ldtk' (Error)
[ERROR]        Error: EBUSY: resource busy or locked, open 'C:/Users/Shmellyorc/Documents/Pizzamon/Pizzamon/Content/Map/Pizzamon.ldtk'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.writeFileSync (node:fs:2153:35)
    at Function.dn_js_NodeTools.writeFileString (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:80121:13)
    at Object.cb (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:215697:21)
    at ui_modal_Progress.update (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:220409:8)
    at Function.dn_Process._doMainUpdate (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:223:4)
    at Function.dn_Process._doMainUpdate (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:266:15)
    at Function.dn_Process._doMainUpdate (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:266:15)
    at Function.dn_Process.updateAll (file:///C:/Users/Shmellyorc/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:734:14)

[GENERAL]      
#0 App
 |--- #1874 page.Editor
       |--- #1875 misc.FileWatcher
       |--- #1876 display.WorldRender
       |--- #1877 display.LevelRender
       |--- #1878 display.Camera
       |--- #1879 display.Rulers[--]
       |--- #1880 tool.SelectionTool[--]
       |--- #1881 tool.lt.DoNothing[--]
       |--- #1882 WorldTool
       |--- #1883 tool.PanView[--]
       |--- #2019 tool.lt.IntGridTool [PAUSED][--]
       |--- #2022 tool.lt.TileTool [PAUSED][--]
       |--- #2024 tool.lt.TileTool[--]
       |--- #2029 tool.lt.IntGridTool [PAUSED][--]
       |--- #2486 tool.lt.EntityTool [PAUSED][--]
       |--- #3879 display.EntityRender
       |--- #3880 ui.ProjectSaver
       |--- #3881 ui.modal.MetaProgress
       |--- #3884 ui.modal.Progress
 |--- #3885 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by ZEG-John** [comment]
I believe I got a similar crash. 

I was painting a tile and then the app crashed. When i reopened it using the "auto recovery" it tried to delete like half my maps, and I got like 99+ errors. I was able to recover them by reverting them in git. I was then able to open the project apparently sanely but it was very concerning, especially when it deleted a ton of maps.

CRASH LOG: (I have redacted my user directory and project directory as USERNAME and THE_PROJEcT_PATH respectively):
```
[USERACTION]   2024-03-29 23:02:15   IntGridTool: mode=Add, in LayerInst#23 "BuildingTilesInt" [IntGrid]
[SAVE]         2024-03-29 23:02:16   Preparing project saving: F:/THE_PROJECT_PATH/testmap.ldtk...
[SAVE]         2024-03-29 23:02:16   => PreChecks...
[SAVE]         2024-03-29 23:02:16   => BeforeSavingActions...
[EVENT]        2024-03-29 23:02:16   BeforeProjectSaving
[SAVE]         2024-03-29 23:02:16   => AutoLayers...
[GENERAL]      2024-03-29 23:02:16   Progress created.
[RENDER]       2024-03-29 23:02:16   Rendering world bg...
[GENERAL]      2024-03-29 23:02:16   Progress started: : "Preparing levels...", 40 operation(s)
[GENERAL]      2024-03-29 23:02:16   Progress completed: "Preparing levels..." (0s)
[SAVE]         2024-03-29 23:02:16   => SavingMainFile...
[GENERAL]      2024-03-29 23:02:16   Progress created.
[RENDER]       2024-03-29 23:02:16   Rendering world bg...
[GENERAL]      2024-03-29 23:02:16   Progress started: : "Saving main file...", 2 operation(s)
[SAVE]         2024-03-29 23:02:16     Preparing SavingData...
[SAVE]         2024-03-29 23:02:16     Writing F:/THE_PROJECT_PATH/testmap.ldtk...
[GENERAL]      2024-03-29 23:02:16   Progress completed: "Saving main file..." (0s)
[SAVE]         2024-03-29 23:02:16   => SavingExternLevels...
[FILE]         2024-03-29 23:02:16   Emptying dir F:/THE_PROJECT_PATH/testmap (onlyExts=[ldtkl])...
[GENERAL]      2024-03-29 23:02:17   Page started: page.CrashReport()
[FILE]         2024-03-29 23:02:17   Loading page template: crashReport from C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        2024-03-29 23:02:17   EBUSY: resource busy or locked, unlink 'F:/THE_PROJECT_PATH/testmap/Level_32.ldtkl' (Error)
[ERROR]        2024-03-29 23:02:17   Error: EBUSY: resource busy or locked, unlink 'F:/THE_PROJECT_PATH/testmap/Level_32.ldtkl'
    at Object.unlinkSync (node:fs:1780:3)
    at misc_JsTools.removeDirFiles (file:///C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:230592:15)
    at ui_ProjectSaver.initDir (file:///C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:287538:17)
    at ui_ProjectSaver.beginState (file:///C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:286750:10)
    at ui_ProjectSaver.beginNextState (file:///C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:286395:8)
    at ui_modal_Progress.onComplete (file:///C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:286719:13)
    at ui_modal_Progress.update (file:///C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:292611:10)
    at dn_Process._doMainUpdate (file:///C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:405:4)
    at dn_Process._doMainUpdate (file:///C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:432:15)
    at dn_Process._doMainUpdate (file:///C:/Users/USERNAME/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:432:15)

[GENERAL]      2024-03-29 23:02:17   
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.EntityTool [PAUSED][--]
       |--- #190 tool.lt.IntGridTool [PAUSED][--]
       |--- #194 tool.lt.IntGridTool[--]
       |--- #197 tool.lt.TileTool [PAUSED][--]
       |--- #216 tool.lt.IntGridTool [PAUSED][--]
       |--- #249 tool.lt.DoNothing [PAUSED][--]
       |--- #3411 display.EntityRender
       |--- #3412 display.EntityRender
       |--- #3413 display.EntityRender
       |--- #3414 display.EntityRender
       |--- #3415 display.EntityRender
       |--- #3416 display.EntityRender
       |--- #3417 display.EntityRender
       |--- #3418 display.EntityRender
       |--- #3419 display.EntityRender
       |--- #3420 display.EntityRender
       |--- #3421 display.EntityRender
       |--- #3422 display.EntityRender
       |--- #3423 display.EntityRender
       |--- #3424 display.EntityRender
       |--- #3425 display.EntityRender
       |--- #3426 display.EntityRender
       |--- #3427 display.EntityRender
       |--- #3428 display.EntityRender
       |--- #3429 display.EntityRender
       |--- #3430 display.EntityRender
       |--- #3431 display.EntityRender
       |--- #3432 display.EntityRender
       |--- #3433 display.EntityRender
       |--- #3434 display.EntityRender
       |--- #3435 display.EntityRender
       |--- #3436 display.EntityRender
       |--- #3437 display.EntityRender
       |--- #3438 display.EntityRender
       |--- #3439 display.EntityRender
       |--- #3440 display.EntityRender
       |--- #3441 display.EntityRender
       |--- #3442 display.EntityRender
       |--- #3443 display.EntityRender
       |--- #3444 display.EntityRender
       |--- #3454 ui.ProjectSaver
       |--- #3455 ui.modal.MetaProgress
       |--- #3457 ui.modal.Progress
 |--- #3458 page.CrashReport
`
```
