### ISSUE TITLE
crash when trying to connect entities

### ISSUE THREAD

**Issue by PoolloverNathan** [deepnight/ldtk#701]
null doesn't really have properties last I checked

Stack:
```
LDtk version: 1.1.3-64bits
Cannot read properties of null (reading 'getEntityRefFieldTo')
TypeError
TypeError: Cannot read properties of null (reading 'getEntityRefFieldTo')
    at data_inst_EntityInstance.tidyLostSymmetricalEntityRefs (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:34540:16)
    at data_inst_FieldInstance.setEntityRefTo (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:36000:12)
    at ui_vp_EntityRefPicker.vp.onPickValue (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:211178:9)
    at ui_vp_EntityRefPicker.onPick (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:219289:8)
    at ui_vp_EntityRefPicker.onPick (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:231962:35)
    at ui_vp_EntityRefPicker.onMouseDown (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:219307:10)
    at page_Editor.onMouseDown (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:180745:22)
    at page_Editor.onHeapsEvent (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:180687:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:95519:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:138057:6)
```
Processes:
```
#0 App
 |--- #80 page.Editor
       |--- #81 misc.FileWatcher
       |--- #82 display.WorldRender
       |--- #83 display.LevelRender
       |--- #84 display.Camera
       |--- #85 display.Rulers[--]
       |--- #86 tool.SelectionTool[--]
       |--- #87 tool.lt.DoNothing[--]
       |--- #88 WorldTool
       |--- #89 tool.PanView[--]
       |--- #1378 tool.lt.IntGridTool [PAUSED][--]
       |--- #1384 tool.lt.TileTool [PAUSED][--]
       |--- #1506 tool.lt.TileTool [PAUSED][--]
       |--- #1534 tool.lt.EntityTool[--]
       |--- #1941 tool.lt.IntGridTool [PAUSED][--]
       |--- #2200 ui.vp.EntityRefPicker
       |--- #2209 display.EntityRender
```

Log:
```
[FILE]         Reading HTML template entityInstanceEditor from cache
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template entityInstanceEditor from cache
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template entityInstanceEditor from cache
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[FILE]         Loading HTML template valuePicker
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template worldPanel from cache
[FILE]         Reading HTML template levelInstanceForm from cache
[RENDER]       Rendering world level data.Level.Level_3(#15)...
[RENDER]       Rendering world bg...
[EVENT]        WorldDepthSelected
[EVENT]        WorldDepthSelected
[EVENT]        WorldDepthSelected
[EVENT]        WorldDepthSelected
[WARNING]      Full level render requested
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template worldPanel from cache
[FILE]         Reading HTML template levelInstanceForm from cache
[RENDER]       Rendering world level data.Level.Level_3(#15)...
[RENDER]       Rendering world bg...
[EVENT]        LevelSelected 15
[RENDER]       Rendering world level data.Level.Level_3(#15)...
[RENDER]       Rendering world level fields data.Level.Level_3(#15)...
[WARNING]      Full level render requested
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template worldPanel from cache
[FILE]         Reading HTML template levelInstanceForm from cache
[RENDER]       Rendering world level data.Level.Level_3(#15)...
[RENDER]       Rendering world bg...
[EVENT]        WorldDepthSelected
[EVENT]        WorldDepthSelected
[EVENT]        WorldDepthSelected
[EVENT]        LevelSelected 28
[WARNING]      Full level render requested
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level data.Level.Level_3(#15)...
[RENDER]       Rendering world level fields data.Level.Level_7(#28)...
[RENDER]       Rendering world level data.Level.Level_7(#28)...
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'getEntityRefFieldTo') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'getEntityRefFieldTo')
    at data_inst_EntityInstance.tidyLostSymmetricalEntityRefs (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:34540:16)
    at data_inst_FieldInstance.setEntityRefTo (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:36000:12)
    at ui_vp_EntityRefPicker.vp.onPickValue (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:211178:9)
    at ui_vp_EntityRefPicker.onPick (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:219289:8)
    at ui_vp_EntityRefPicker.onPick (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:231962:35)
    at ui_vp_EntityRefPicker.onMouseDown (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:219307:10)
    at page_Editor.onMouseDown (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:180745:22)
    at page_Editor.onHeapsEvent (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:180687:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:95519:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:138057:6)

[GENERAL]      
#0 App
 |--- #80 page.Editor
       |--- #81 misc.FileWatcher
       |--- #82 display.WorldRender
       |--- #83 display.LevelRender
       |--- #84 display.Camera
       |--- #85 display.Rulers[--]
       |--- #86 tool.SelectionTool[--]
       |--- #87 tool.lt.DoNothing[--]
       |--- #88 WorldTool
       |--- #89 tool.PanView[--]
       |--- #1378 tool.lt.IntGridTool [PAUSED][--]
       |--- #1384 tool.lt.TileTool [PAUSED][--]
       |--- #1506 tool.lt.TileTool [PAUSED][--]
       |--- #1534 tool.lt.EntityTool[--]
       |--- #1941 tool.lt.IntGridTool [PAUSED][--]
       |--- #2200 ui.vp.EntityRefPicker
       |--- #2209 display.EntityRender
 |--- #2210 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Thanks for the report. However, it's important to provide some information about what you were doing exactly before the crash happened. 

I will mark this issue as solved as some related bug was fixed, but feel free to reopen if this error happens again in update 1.2.0.
