### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by imnotdream** [deepnight/ldtk#741]
Here is the info LDtk said to provide so you could fix it. No clue why it wont open my project.
Stack:
```
LDtk version: 1.1.3-64bits
Cannot read properties of null (reading 'externalLevels')
TypeError
TypeError: Cannot read properties of null (reading 'externalLevels')
    at Object.cb (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:214580:8)
    at ui_modal_Progress.update (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:220409:8)
    at Function.dn_Process._doMainUpdate (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:223:4)
    at Function.dn_Process.updateAll (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:734:14)
    at Boot.update (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:4571:14)
    at Boot.mainLoop (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:4533:8)
    at hxd_System.browserLoop (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:138601:14)
```
Processes:
```
#0 App
 |--- #4 page.Home
 |--- #7 page.Home
#6 ui.modal.Progress
#8 ui.modal.dialog.LogPrint
```

Log:
```
[BOOT]         ExePath: C:/Users/dyckp/AppData/Local/Programs/ldtk
[BOOT]         Assets: C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets
[BOOT]         ExtraFiles: C:/Users/dyckp/AppData/Local/Programs/ldtk/extraFiles
[BOOT]         CWD: C:\Users\dyckp\AppData\Local\Programs\ldtk\
[BOOT]         Display: 1366x768
[BOOT]         Args: soloValues=[], args=[]
[FILE]         Loading settings from C:/Users/dyckp/AppData/Roaming/LDtk/settings...
[BOOT]         AppZoomFactor: 1
[BOOT]         Calling appReady...
[UPDATE]       Looking for update
[BOOT]         Start args: path=null levelIndex=null
[BOOT]         Loading Home...
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/home.html
[ERROR]        Problem with recent dir: C:/Users/dyckp/OneDrive/Documents/GDevelop projects/tilemap
[DEBUG]        samplesDir=C:/Users/dyckp/AppData/Local/Programs/ldtk/extraFiles/samples
[ERROR]        Project file not found
[ERROR]        Failed to load project: C:/Users/dyckp/OneDrive/Documents/GDevelop projects/tilemap/ne/grass_level_1.ldtk levelIdx=undefined
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/home.html
[ERROR]        Problem with recent dir: C:/Users/dyckp/OneDrive/Documents/GDevelop projects/tilemap
[DEBUG]        samplesDir=C:/Users/dyckp/AppData/Local/Programs/ldtk/extraFiles/samples
[ERROR]        Project file not found
[ERROR]        Project file not found
[ERROR]        Failed to load project: C:/Users/dyckp/OneDrive/Documents/GDevelop projects/tilemap/Platformer.ldtk levelIdx=undefined
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/home.html
[ERROR]        Problem with recent dir: C:/Users/dyckp/OneDrive/Documents/GDevelop projects/tilemap
[DEBUG]        samplesDir=C:/Users/dyckp/AppData/Local/Programs/ldtk/extraFiles/samples
[ERROR]        Project file not found
[GENERAL]      Progress created.
[GENERAL]      Progress started: : "grass_level_1.json: Project...", 5 operation(s)
[LOAD]         Loading project grass_level_1.json...
[LOAD]           Project appBuildId=undefined appJsonVersion=1.1.3 jsonVersion=undefined
[LOAD]           Need re-saving (reason: json appBuildId is older)
[LOAD]           Need re-saving (reason: json version is older than app)
[ERROR]        TypeError: Cannot read properties of undefined (reading 'layers')
[ERROR]        Failed to load project: C:/Users/dyckp/OneDrive/Documents/GDevelop projects/tilemap/ne/grass_level_1.json levelIdx=undefined
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/home.html
[ERROR]        Problem with recent dir: C:/Users/dyckp/OneDrive/Documents/GDevelop projects/tilemap
[DEBUG]        samplesDir=C:/Users/dyckp/AppData/Local/Programs/ldtk/extraFiles/samples
[FILE]         Loading HTML template logPrint
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'externalLevels') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'externalLevels')
    at Object.cb (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:214580:8)
    at ui_modal_Progress.update (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:220409:8)
    at Function.dn_Process._doMainUpdate (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:223:4)
    at Function.dn_Process.updateAll (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:734:14)
    at Boot.update (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:4571:14)
    at Boot.mainLoop (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:4533:8)
    at hxd_System.browserLoop (file:///C:/Users/dyckp/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:138601:14)

[GENERAL]      
#0 App
 |--- #4 page.Home
 |--- #7 page.Home
 |--- #9 page.CrashReport
#6 ui.modal.Progress
#8 ui.modal.dialog.LogPrint

```

**Comment by deepnight** [comment]
Hi,
Have you renamed the project manually (ie. outside of the LDtk app)?
