### ISSUE TITLE
Bug Report (using Linux version)

### ISSUE THREAD

**Issue by AetherSky-arch** [deepnight/ldtk#750]
Stack:
```
LDtk version: 1.1.3-64bits
EROFS: read-only file system, open '/tmp/.mount_LDtk 1Kdu3Vl/extraFiles/samples/AutoLayers_1_basic.ldtk'
Error
Error: EROFS: read-only file system, open '/tmp/.mount_LDtk 1Kdu3Vl/extraFiles/samples/AutoLayers_1_basic.ldtk'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.writeFileSync (node:fs:2153:35)
    at Function.dn_js_NodeTools.writeFileString (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:80122:13)
    at Object.cb (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:215698:21)
    at ui_modal_Progress.update (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:220410:8)
    at Function.dn_Process._doMainUpdate (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:224:4)
    at Function.dn_Process.updateAll (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:735:14)
    at Boot.update (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:4572:14)
    at Boot.mainLoop (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:4534:8)
```
Processes:
```
#0 App
 |--- #1 page.Home
       |--- #2 ui.ProjectSaver
#3 ui.modal.MetaProgress
#5 ui.modal.Progress
```

Log:
```


[BOOT]         App started
[BOOT]         Version: 1.1.3-64bits (build 458364)
[BOOT]         ExePath: /tmp/.mount_LDtk 1Kdu3Vl
[BOOT]         Assets: /tmp/.mount_LDtk 1Kdu3Vl/resources/app.asar/assets
[BOOT]         ExtraFiles: /tmp/.mount_LDtk 1Kdu3Vl/extraFiles
[BOOT]         CWD: /home/ari_cover/Téléchargements/
[BOOT]         Display: 1600x900
[BOOT]         Args: soloValues=[], args=[]
[FILE]         Loading settings from /home/ari_cover/.config/LDtk/settings...
[BOOT]         AppZoomFactor: 1
[UPDATE]       Fetching latest version from GitHub...
[BOOT]         Calling appReady...
[BOOT]         Start args: path=null levelIndex=null
[BOOT]         Loading Home...
[GENERAL]      Page started: page.Home()
[FILE]         Loading page template: home from /tmp/.mount_LDtk 1Kdu3Vl/resources/app.asar/assets/tpl/pages/home.html
[DEBUG]        samplesDir=/tmp/.mount_LDtk 1Kdu3Vl/extraFiles/samples
[UPDATE]       Found 1.1.3
[UPDATE]       No new update.
[SAVE]         Preparing project saving: /tmp/.mount_LDtk 1Kdu3Vl/extraFiles/samples/AutoLayers_1_basic.ldtk...
[SAVE]         => PreChecks...
[GENERAL]      Progress created.
[GENERAL]      Progress started: : "Preparing levels...", 1 operation(s)
[GENERAL]      Progress completed: "Preparing levels..." (0s)
[SAVE]         => SavingMainFile...
[GENERAL]      Progress created.
[GENERAL]      Progress started: : "Saving main file...", 2 operation(s)
[SAVE]           Preparing SavingData...
[SAVE]           Writing /tmp/.mount_LDtk 1Kdu3Vl/extraFiles/samples/AutoLayers_1_basic.ldtk...
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from /tmp/.mount_LDtk 1Kdu3Vl/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        EROFS: read-only file system, open '/tmp/.mount_LDtk 1Kdu3Vl/extraFiles/samples/AutoLayers_1_basic.ldtk' (Error)
[ERROR]        Error: EROFS: read-only file system, open '/tmp/.mount_LDtk 1Kdu3Vl/extraFiles/samples/AutoLayers_1_basic.ldtk'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1800)
    at Object.writeFileSync (node:fs:2153:35)
    at Function.dn_js_NodeTools.writeFileString (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:80122:13)
    at Object.cb (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:215698:21)
    at ui_modal_Progress.update (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:220410:8)
    at Function.dn_Process._doMainUpdate (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:224:4)
    at Function.dn_Process.updateAll (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:735:14)
    at Boot.update (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:4572:14)
    at Boot.mainLoop (file:///tmp/.mount_LDtk%201Kdu3Vl/resources/app.asar/assets/js/renderer.js:4534:8)

[GENERAL]      
#0 App
 |--- #1 page.Home
       |--- #2 ui.ProjectSaver
 |--- #6 page.CrashReport
#3 ui.modal.MetaProgress
#5 ui.modal.Progress

```

**Comment by deepnight** [comment]
Somewhat fixed in 1.2.0. You should now see proper error messages in this case.
