### ISSUE TITLE
Crash when opening a menu while picking a tile

### ISSUE THREAD

**Issue by Cammin** [deepnight/ldtk#798]
An example of how to reproduce:
-have an entity with a tile as it's editor visual and try to change it's tile to open the tile picker
-start holding the mouse on a tile (or dragging multiple, doesn't matter)
-press f12 which opens project settings (still hold mouse button)
-let go of the mouse button to crash

- This applies to more than just pressing f12. if there's any keybind that can open another menu, then it may be able to cause this issue.
- This bug may also apply to the tile picker when selecting a tile field, or when selecting a tile for auto rules, or any other instances of tile picking.
- I've seen some crash instances in the auto rules picker where it crashes by opening a menu with a keybind without even having to hold the mouse. Might be a separate bug for that specific scenario.

Stack:
```
LDtk version: 1.2.3-64bits
Cannot read properties of null (reading 'baseFps')
TypeError
TypeError: Cannot read properties of null (reading 'baseFps')
    at ui_Modal.close (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:250110:41)
    at ui_Tileset.tp.onSelectAnything (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203468:7)
    at ui_Tileset.modifySelection (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:255401:8)
    at ui_Tileset.onDocMouseUp (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:255297:10)
    at HTMLDocument.dispatch (C:\Users\cameo\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at HTMLDocument.v.handle (C:\Users\cameo\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)
```
Processes:
```
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #15 tool.lt.EntityTool [PAUSED][--]
       |--- #38 display.EntityRender
       |--- #39 display.EntityRender
       |--- #40 display.EntityRender
       |--- #41 display.EntityRender
       |--- #42 display.EntityRender
       |--- #43 display.EntityRender
       |--- #44 display.EntityRender
       |--- #45 display.EntityRender
       |--- #46 display.EntityRender
       |--- #47 display.EntityRender
       |--- #48 display.EntityRender
       |--- #55 tool.lt.IntGridTool[--]
       |--- #67 ui.modal.dialog.EditAppSettings
```

Log:
```
[RENDER]       Rendering world level data.Level#a3030e70-66b0-11ec-9cd7-3fe74f53b9c3 "Everything"...
[RENDER]       Rendering world level fields data.Level#a3030e70-66b0-11ec-9cd7-3fe74f53b9c3 "Everything"...
[RENDER]       Rendering world bg...
[GENERAL]      Progress completed: "Test_file_for_API_showing_all_features.ldtk: Project..." (0.5s)
[GENERAL]      Relocation canceled
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #52 ui.modal.panel.EditLayerDefs
[FILE]         Loading HTML template editLayerDefs
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #58 ui.modal.panel.EditEntityDefs
[USERACTION]   Closed panel #52 ui.modal.panel.EditLayerDefs
[FILE]         Loading HTML template editEntityDefs
[FILE]         Loading HTML template fieldDefsForm
[FILE]         Loading HTML template pivotEditor
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template pivotEditor from cache
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Closed panel #58 ui.modal.panel.EditEntityDefs
[FILE]         Loading HTML template editAppSettings
[RENDER]       Rendering world bg...
[EVENT]        ToolValueSelected
[EVENT]        EntityDefChanged
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'baseFps') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'baseFps')
    at ui_Modal.close (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:250110:41)
    at ui_Tileset.tp.onSelectAnything (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203468:7)
    at ui_Tileset.modifySelection (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:255401:8)
    at ui_Tileset.onDocMouseUp (file:///C:/Users/cameo/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:255297:10)
    at HTMLDocument.dispatch (C:\Users\cameo\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at HTMLDocument.v.handle (C:\Users\cameo\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)

[GENERAL]      
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #15 tool.lt.EntityTool [PAUSED][--]
       |--- #38 display.EntityRender
       |--- #39 display.EntityRender
       |--- #40 display.EntityRender
       |--- #41 display.EntityRender
       |--- #42 display.EntityRender
       |--- #43 display.EntityRender
       |--- #44 display.EntityRender
       |--- #45 display.EntityRender
       |--- #46 display.EntityRender
       |--- #47 display.EntityRender
       |--- #48 display.EntityRender
       |--- #55 tool.lt.IntGridTool[--]
       |--- #67 ui.modal.dialog.EditAppSettings
 |--- #68 page.CrashReport

[CACHE]        Caching image atlas/Beach by deepnight.png...
[CACHE]         -> identified as Png
[CACHE]         -> base64 144844
[CACHE]         -> pixels 320x240
[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Fixed in 1.2.4
