### ISSUE TITLE
Crash when selecting tile that does not have a tileset

### ISSUE THREAD

**Issue by Miepee** [deepnight/ldtk#868]
Relatively simple way to crash the tool:
- Create a tile layer and assign a default tileset to it (like the internal icons)
- draw something in the room from that layer
- Change default tileset for that layer to "-- Select a tileset --"
- Select any of the drawn tiles with ALT+LMB

Stacktrace:
<details> 
  <summary>Click to reveal </summary>

```
LDtk version: 1.2.6-64bits
Cannot read properties of null (reading 'getSavedSelectionFor')
TypeError
TypeError: Cannot read properties of null (reading 'getSavedSelectionFor')
    at tool_SelectionTool.select (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:228114:80)
    at tool_SelectionTool.startUsing (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:231834:11)
    at page_Editor.onMouseDown (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:213002:24)
    at page_Editor.onHeapsEvent (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:212914:9)
    at h2d_Scene.dispatchListeners (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:123762:4)
    at hxd_SceneEvents.dispatchListeners (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:166925:6)
    at hxd_SceneEvents.emitEvent (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:166755:9)
    at hxd_SceneEvents.checkEvents (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:166841:10)
    at Boot.mainLoop (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:5440:16)
    at hxd_System.browserLoop (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:167543:14)
``` 
Processes:
```
#0 App
 |--- #2300 page.Editor
       |--- #2301 misc.FileWatcher
       |--- #2302 display.WorldRender
       |--- #2303 display.LevelRender
       |--- #2304 display.Camera
       |--- #2305 display.Rulers[--]
       |--- #2306 tool.SelectionTool[Add] [RUNNING]
       |--- #2307 tool.lt.DoNothing[--]
       |--- #2308 WorldTool
       |--- #2309 tool.PanView[--]
       |--- #4494 display.EntityRender
       |--- #4495 display.EntityRender
       |--- #4496 display.EntityRender
       |--- #4497 display.EntityRender
       |--- #4498 display.EntityRender
       |--- #4499 display.EntityRender
       |--- #4500 display.EntityRender
       |--- #4501 display.EntityRender
       |--- #4502 display.EntityRender
       |--- #4503 display.EntityRender
       |--- #4504 display.EntityRender
       |--- #4505 display.EntityRender
       |--- #4506 display.EntityRender
       |--- #4507 display.EntityRender
       |--- #4508 display.EntityRender
       |--- #4509 display.EntityRender
       |--- #4510 display.EntityRender
       |--- #4511 display.EntityRender
       |--- #4512 display.EntityRender
       |--- #4513 display.EntityRender
       |--- #4514 display.EntityRender
       |--- #4515 display.EntityRender
       |--- #4702 tool.lt.TileTool[--]
```

Log:
```
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #4690 ui.modal.panel.EditLayerDefs
[FILE]         Reading HTML template editLayerDefs from cache
[FILE]         Reading HTML template pivotEditor from cache
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[EVENT]        LayerDefChanged 1037
[FILE]         Reading HTML template pivotEditor from cache
[RENDER]       Rendering world level data.Level#f97d77a0-9f30-11ed-931c-23a60d8f3791 "Level_0"...
[RENDER]       Rendering world bg...
[USERACTION]   Closed panel #4690 ui.modal.panel.EditLayerDefs
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[EVENT]        ToolValueSelected
[EVENT]        LayerInstanceEditedByTool
[USERACTION]   TileTool: mode=Add, in LayerInst#1037 "Tiles5" [Tiles]
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #4698 ui.modal.panel.EditLayerDefs
[FILE]         Reading HTML template editLayerDefs from cache
[FILE]         Reading HTML template pivotEditor from cache
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[EVENT]        LayerDefChanged 1037
[FILE]         Reading HTML template pivotEditor from cache
[RENDER]       Rendering world level data.Level#f97d77a0-9f30-11ed-931c-23a60d8f3791 "Level_0"...
[RENDER]       Rendering world bg...
[USERACTION]   Closed panel #4698 ui.modal.panel.EditLayerDefs
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from /tmp/.mount_LDtk 1PCIPCE/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'getSavedSelectionFor') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'getSavedSelectionFor')
    at tool_SelectionTool.select (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:228114:80)
    at tool_SelectionTool.startUsing (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:231834:11)
    at page_Editor.onMouseDown (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:213002:24)
    at page_Editor.onHeapsEvent (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:212914:9)
    at h2d_Scene.dispatchListeners (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:123762:4)
    at hxd_SceneEvents.dispatchListeners (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:166925:6)
    at hxd_SceneEvents.emitEvent (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:166755:9)
    at hxd_SceneEvents.checkEvents (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:166841:10)
    at Boot.mainLoop (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:5440:16)
    at hxd_System.browserLoop (file:///tmp/.mount_LDtk%201PCIPCE/resources/app.asar/assets/js/renderer.js:167543:14)

[GENERAL]      
#0 App
 |--- #2300 page.Editor
       |--- #2301 misc.FileWatcher
       |--- #2302 display.WorldRender
       |--- #2303 display.LevelRender
       |--- #2304 display.Camera
       |--- #2305 display.Rulers[--]
       |--- #2306 tool.SelectionTool[Add] [RUNNING]
       |--- #2307 tool.lt.DoNothing[--]
       |--- #2308 WorldTool
       |--- #2309 tool.PanView[--]
       |--- #4494 display.EntityRender
       |--- #4495 display.EntityRender
       |--- #4496 display.EntityRender
       |--- #4497 display.EntityRender
       |--- #4498 display.EntityRender
       |--- #4499 display.EntityRender
       |--- #4500 display.EntityRender
       |--- #4501 display.EntityRender
       |--- #4502 display.EntityRender
       |--- #4503 display.EntityRender
       |--- #4504 display.EntityRender
       |--- #4505 display.EntityRender
       |--- #4506 display.EntityRender
       |--- #4507 display.EntityRender
       |--- #4508 display.EntityRender
       |--- #4509 display.EntityRender
       |--- #4510 display.EntityRender
       |--- #4511 display.EntityRender
       |--- #4512 display.EntityRender
       |--- #4513 display.EntityRender
       |--- #4514 display.EntityRender
       |--- #4515 display.EntityRender
       |--- #4702 tool.lt.TileTool[--]
 |--- #4703 page.CrashReport

[FILE]         Cleared all file watches
```

</details>

**Comment by deepnight** [comment]
Fixed in 1.2.6
