### ISSUE TITLE
Crash when attempting to use the auto layer assistant on an auto layer without a tileset

### ISSUE THREAD

**Issue by PoolloverNathan** [deepnight/ldtk#886]
**Steps to reproduce**
1. Create an autotile layer without a tileset
2. Open the layer's rules
3. Click Use Assistant

**Expected outcome**
The Use Assistant button would be disabled since there is no tileset to pick tiles from

**Actual outcome**
A crash occurs due to a missing null check

<details>
<summary>Error info</summary>

Stack:
```
LDtk version: 1.2.5-64bits
Cannot read properties of null (reading 'pxWid')
TypeError
TypeError: Cannot read properties of null (reading 'pxWid')
    at new ui_Tileset (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:254775:44)
    at new ui_modal_dialog_RulesWizard (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:262496:17)
    at ui_modal_panel_EditAllAutoLayerRules.doUseWizard (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:265537:3)
    at Object.cb (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:265184:12)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:257261:6)
    at HTMLButtonElement.dispatch (C:\Users\natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (C:\Users\natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.EntityTool [PAUSED][--]
       |--- #163 tool.lt.DoNothing[--]
       |--- #165 display.EntityRender
       |--- #166 display.EntityRender
       |--- #167 display.EntityRender
       |--- #168 display.EntityRender
       |--- #169 display.EntityRender
       |--- #170 display.EntityRender
       |--- #171 display.EntityRender
       |--- #172 display.EntityRender
       |--- #173 display.EntityRender
       |--- #174 display.EntityRender
       |--- #175 display.EntityRender
       |--- #176 display.EntityRender
       |--- #177 display.EntityRender
       |--- #178 display.EntityRender
       |--- #179 display.EntityRender
       |--- #180 display.EntityRender
       |--- #181 display.EntityRender
       |--- #182 display.EntityRender
       |--- #183 display.EntityRender
       |--- #184 display.EntityRender
       |--- #185 display.EntityRender
       |--- #186 display.EntityRender
       |--- #187 display.EntityRender
       |--- #188 display.EntityRender
       |--- #189 display.EntityRender
       |--- #190 display.EntityRender
       |--- #191 display.EntityRender
       |--- #192 display.EntityRender
       |--- #193 display.EntityRender
       |--- #194 display.EntityRender
       |--- #195 display.EntityRender
       |--- #196 display.EntityRender
       |--- #197 display.EntityRender
       |--- #198 display.EntityRender
       |--- #199 display.EntityRender
       |--- #200 display.EntityRender
       |--- #201 display.EntityRender
       |--- #202 display.EntityRender
       |--- #203 display.EntityRender
       |--- #204 display.EntityRender
       |--- #205 display.EntityRender
       |--- #206 display.EntityRender
       |--- #207 display.EntityRender
       |--- #208 display.EntityRender
       |--- #209 display.EntityRender
       |--- #210 display.EntityRender
       |--- #211 display.EntityRender
       |--- #212 display.EntityRender
       |--- #217 ui.modal.panel.EditAllAutoLayerRules
       |--- #218 ui.modal.ContextMenu
       |--- #219 ui.modal.dialog.RulesWizard
```

Log:
```
/* redacted */
[RENDER]       Rendering world level data.Level#491228f0-c640-11ed-b7f3-4b55515ac0a7 "level_0"...
[RENDER]       Rendering world level fields data.Level#491228f0-c640-11ed-b7f3-4b55515ac0a7 "level_0"...
[RENDER]       Rendering world bg...
[GENERAL]      Progress completed: "world.ldtk: Project..." (1.6s)
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #160 ui.modal.panel.EditLayerDefs
[FILE]         Loading HTML template editLayerDefs
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[TIDY]         Lost default enum value in FieldDef FieldDef.door_type(F_Enum(42), default=open)[.*]
[TIDY]         Fixed layer instance array in data.Level#491228f0-c640-11ed-b7f3-4b55515ac0a7 "level_0" (order mismatch or missing layer instance)
[TIDY]         Added missing layer instance autolayer in data.Level#491228f0-c640-11ed-b7f3-4b55515ac0a7 "level_0"
[EVENT]        LayerInstanceSelected
[EVENT]        LayerDefAdded
[GENERAL]      Progress created.
[RENDER]       Rendered level UI
[RENDER]       Rendering world level data.Level#491228f0-c640-11ed-b7f3-4b55515ac0a7 "level_0"...
[ERROR]        missing autoTilesCache in LayerInst#72 "autolayer" [AutoLayer]
[WARNING]      Full level render requested
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "Updating auto-layers...", 1 operation(s)
[WARNING]      All rules applied in LayerInst#72 "autolayer" [AutoLayer]
[GENERAL]      Progress completed: "Updating auto-layers..." (0.1s)
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Closed panel #160 ui.modal.panel.EditLayerDefs
[USERACTION]   Opened panel #217 ui.modal.panel.EditAllAutoLayerRules
[FILE]         Loading HTML template editAllAutoLayerRules
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[FILE]         Loading HTML template rulesWizard.html
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'pxWid') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'pxWid')
    at new ui_Tileset (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:254775:44)
    at new ui_modal_dialog_RulesWizard (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:262496:17)
    at ui_modal_panel_EditAllAutoLayerRules.doUseWizard (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:265537:3)
    at Object.cb (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:265184:12)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:257261:6)
    at HTMLButtonElement.dispatch (C:\Users\natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (C:\Users\natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.EntityTool [PAUSED][--]
       |--- #163 tool.lt.DoNothing[--]
       |--- #165 display.EntityRender
       |--- #166 display.EntityRender
       |--- #167 display.EntityRender
       |--- #168 display.EntityRender
       |--- #169 display.EntityRender
       |--- #170 display.EntityRender
       |--- #171 display.EntityRender
       |--- #172 display.EntityRender
       |--- #173 display.EntityRender
       |--- #174 display.EntityRender
       |--- #175 display.EntityRender
       |--- #176 display.EntityRender
       |--- #177 display.EntityRender
       |--- #178 display.EntityRender
       |--- #179 display.EntityRender
       |--- #180 display.EntityRender
       |--- #181 display.EntityRender
       |--- #182 display.EntityRender
       |--- #183 display.EntityRender
       |--- #184 display.EntityRender
       |--- #185 display.EntityRender
       |--- #186 display.EntityRender
       |--- #187 display.EntityRender
       |--- #188 display.EntityRender
       |--- #189 display.EntityRender
       |--- #190 display.EntityRender
       |--- #191 display.EntityRender
       |--- #192 display.EntityRender
       |--- #193 display.EntityRender
       |--- #194 display.EntityRender
       |--- #195 display.EntityRender
       |--- #196 display.EntityRender
       |--- #197 display.EntityRender
       |--- #198 display.EntityRender
       |--- #199 display.EntityRender
       |--- #200 display.EntityRender
       |--- #201 display.EntityRender
       |--- #202 display.EntityRender
       |--- #203 display.EntityRender
       |--- #204 display.EntityRender
       |--- #205 display.EntityRender
       |--- #206 display.EntityRender
       |--- #207 display.EntityRender
       |--- #208 display.EntityRender
       |--- #209 display.EntityRender
       |--- #210 display.EntityRender
       |--- #211 display.EntityRender
       |--- #212 display.EntityRender
       |--- #217 ui.modal.panel.EditAllAutoLayerRules
       |--- #218 ui.modal.ContextMenu
       |--- #219 ui.modal.dialog.RulesWizard
 |--- #220 page.CrashReport

[FILE]         Cleared all file watches
```

</details>

**Comment by deepnight** [comment]
Fixed in 1.2.6
