### ISSUE TITLE
"Cannot read properties of null" after deleting entity layer

### ISSUE THREAD

**Issue by Trekken-Games** [deepnight/ldtk#900]
![image](https://user-images.githubusercontent.com/66977646/235517609-93ae2f52-4715-4fa9-ab2f-0c332bc28d0a.png)

The bug occurs when I select any layer that isn't the first layer in the layers panel and delete an entity layer that isn't empty. I can delete empty entity layers and newly created entity layers without issue. I can also delete tile layers and int layers without problems.

ERROR INFO:
Stack:
```
LDtk version: 1.3.0-64bits
Cannot read properties of null (reading 'inactiveOpacity')
TypeError
TypeError: Cannot read properties of null (reading 'inactiveOpacity')
    at display_EntityRender.renderFields (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:53171:60)
    at display_EntityRender.renderAll (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:52674:8)
    at display_EntityRender.onGlobalEvent (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:52648:9)
    at display_LayerRender.onGlobalEvent (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:57477:7)
    at display_LevelRender.onGlobalEvent (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:63950:8)
    at misc_GlobalEventDispatcher.emit (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:205194:4)
    at page_Editor.selectLayerInstance (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:217763:11)
    at ui_modal_panel_EditLayerDefs.updateForm (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:273269:18)
    at ui_modal_panel_EditLayerDefs.select (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:273241:8)
    at ui_modal_panel_EditLayerDefs.deleteLayer (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:272925:8)
```
Processes:
```
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #29 ui.modal.panel.EditLayerDefs
       |--- #32 ui.LastChance
       |--- #33 display.EntityRender
       |--- #34 display.EntityRender
       |--- #35 display.EntityRender
       |--- #36 display.EntityRender
       |--- #37 tool.lt.EntityTool [PAUSED][--]
       |--- #38 ui.modal.ContextMenu
       |--- #39 ui.LastChance
```

Log:
```
[WARNING]      Last chance for: Layer ENT_ITEMS deleted
[TIDY]         Removed lost layer instance in data.Level#8460c060-c640-11ed-b638-11617e7a0c79 "Level_0"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed lost layer instance in data.Level#12232ff0-c640-11ed-b638-2d2559af6d9d "Level_1"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed lost layer instance in data.Level#cc96db60-c640-11ed-b638-1dc1b14b3d16 "Level_2"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed lost layer instance in data.Level#dc900f50-c640-11ed-b638-a39e38e185f8 "Level_3"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed lost layer instance in data.Level#e9752570-c640-11ed-b638-4583861db91e "Level_4"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[EVENT]        LayerDefRemoved 39
[RENDER]       Rendering world level data.Level#8460c060-c640-11ed-b638-11617e7a0c79 "Level_0"...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level data.Level#12232ff0-c640-11ed-b638-2d2559af6d9d "Level_1"...
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[EVENT]        LastChanceEnded
[WARNING]      Last chance for: Layer ENT_ENTITIES deleted
[TIDY]         Removed lost layer instance in data.Level#8460c060-c640-11ed-b638-11617e7a0c79 "Level_0"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed lost layer instance in data.Level#12232ff0-c640-11ed-b638-2d2559af6d9d "Level_1"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed lost layer instance in data.Level#cc96db60-c640-11ed-b638-1dc1b14b3d16 "Level_2"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed lost layer instance in data.Level#dc900f50-c640-11ed-b638-a39e38e185f8 "Level_3"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed lost layer instance in data.Level#e9752570-c640-11ed-b638-4583861db91e "Level_4"
[TIDY]         Removed all autoTilesCache in LayerInst#73 "TILE_AUTO_OVERWORLD" [AutoLayer] (rules can no longer be applied)
[TIDY]         Removed all autoTilesCache in LayerInst#74 "TILE_LIGHTING" [AutoLayer] (rules can no longer be applied)
[EVENT]        LayerInstanceSelected
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'inactiveOpacity') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'inactiveOpacity')
    at display_EntityRender.renderFields (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:53171:60)
    at display_EntityRender.renderAll (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:52674:8)
    at display_EntityRender.onGlobalEvent (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:52648:9)
    at display_LayerRender.onGlobalEvent (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:57477:7)
    at display_LevelRender.onGlobalEvent (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:63950:8)
    at misc_GlobalEventDispatcher.emit (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:205194:4)
    at page_Editor.selectLayerInstance (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:217763:11)
    at ui_modal_panel_EditLayerDefs.updateForm (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:273269:18)
    at ui_modal_panel_EditLayerDefs.select (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:273241:8)
    at ui_modal_panel_EditLayerDefs.deleteLayer (file:///C:/Users/adaml/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:272925:8)

[GENERAL]      
#0 App
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #29 ui.modal.panel.EditLayerDefs
       |--- #32 ui.LastChance
       |--- #33 display.EntityRender
       |--- #34 display.EntityRender
       |--- #35 display.EntityRender
       |--- #36 display.EntityRender
       |--- #37 tool.lt.EntityTool [PAUSED][--]
       |--- #38 ui.modal.ContextMenu
       |--- #39 ui.LastChance
 |--- #40 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Fixed in 1.3.1
