### ISSUE TITLE
Crash report from a bug while saving a level

### ISSUE THREAD

**Issue by mosdevly** [deepnight/ldtk#901]
Stack:
```
LDtk version: 1.3.0-64bits
Cannot read properties of null (reading 'drawTo')
TypeError
TypeError: Cannot read properties of null (reading 'drawTo')
    at display_LayerRender.renderBgToTexture (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:58587:8)
    at display_LayerRender.createBgPng (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:58592:8)
    at ops.push.cb (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256194:26)
    at ui_modal_Progress.update (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:261618:8)
    at dn_Process._doMainUpdate (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1692:4)
    at dn_Process._doMainUpdate (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1719:15)
    at dn_Process._doMainUpdate (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1719:15)
    at dn_Process.updateAll (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1962:14)
    at Boot.update (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5658:14)
    at Boot.mainLoop (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5620:8)
```
Processes:
```
#0 App
 |--- #721 page.Editor
       |--- #722 misc.FileWatcher
       |--- #723 display.WorldRender
       |--- #724 display.LevelRender
       |--- #725 display.Camera
       |--- #726 display.Rulers[--]
       |--- #727 tool.SelectionTool[--]
       |--- #728 tool.lt.DoNothing[--]
       |--- #729 WorldTool
       |--- #730 tool.PanView[--]
       |--- #731 tool.lt.EntityTool [PAUSED][--]
       |--- #751 display.EntityRender
       |--- #752 display.EntityRender
       |--- #755 tool.lt.TileTool[--]
       |--- #760 tool.lt.TileTool [PAUSED][--]
       |--- #780 ui.ProjectSaver
       |--- #781 ui.modal.MetaProgress
       |--- #786 ui.modal.Progress
```

Log:
```
[RENDER]       Rendering world bg...
[GENERAL]      Progress started: : "PNG export", 4 operation(s)
[SAVE]         Level Level_0...
[SAVE]            -> Layer Entities...
[SAVE]            -> Layer Detailing...
[SAVE]            -> Layer Terrain...
[SAVE]            -> Layer Shrubbery...
[SAVE]            -> Layer Walls...
[SAVE]            -> Layer BG_Foliage_2...
[SAVE]            -> Layer BG_Foliage...
[SAVE]            -> Layer BG_Trees...
[SAVE]            -> Layer BG_Hills...
[SAVE]            -> Layer BG_Clouds...
[SAVE]            -> Layer BG_Sky...
[SAVE]         Level Level_1...
[SAVE]            -> Layer Entities...
[SAVE]            -> Layer Detailing...
[SAVE]            -> Layer Terrain...
[SAVE]            -> Layer Shrubbery...
[SAVE]            -> Layer Walls...
[SAVE]            -> Layer BG_Foliage_2...
[SAVE]            -> Layer BG_Foliage...
[SAVE]            -> Layer BG_Trees...
[SAVE]            -> Layer BG_Hills...
[SAVE]            -> Layer BG_Clouds...
[SAVE]            -> Layer BG_Sky...
[SAVE]         Level Level_2...
[SAVE]            -> Layer Entities...
[SAVE]            -> Layer Detailing...
[SAVE]            -> Layer Terrain...
[SAVE]            -> Layer Shrubbery...
[SAVE]            -> Layer Walls...
[SAVE]            -> Layer BG_Foliage_2...
[SAVE]            -> Layer BG_Foliage...
[SAVE]            -> Layer BG_Trees...
[SAVE]            -> Layer BG_Hills...
[SAVE]            -> Layer BG_Clouds...
[SAVE]            -> Layer BG_Sky...
[SAVE]         Level Level_3...
[CACHE]        Caching image levels/png/Level_0__Sky.png...
[CACHE]         -> identified as Unknown
[ERROR]        TypeError: Cannot read properties of null (reading 'length')
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'drawTo') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'drawTo')
    at display_LayerRender.renderBgToTexture (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:58587:8)
    at display_LayerRender.createBgPng (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:58592:8)
    at ops.push.cb (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256194:26)
    at ui_modal_Progress.update (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:261618:8)
    at dn_Process._doMainUpdate (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1692:4)
    at dn_Process._doMainUpdate (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1719:15)
    at dn_Process._doMainUpdate (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1719:15)
    at dn_Process.updateAll (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:1962:14)
    at Boot.update (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5658:14)
    at Boot.mainLoop (file:///C:/Users/publi/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:5620:8)

[GENERAL]      
#0 App
 |--- #721 page.Editor
       |--- #722 misc.FileWatcher
       |--- #723 display.WorldRender
       |--- #724 display.LevelRender
       |--- #725 display.Camera
       |--- #726 display.Rulers[--]
       |--- #727 tool.SelectionTool[--]
       |--- #728 tool.lt.DoNothing[--]
       |--- #729 WorldTool
       |--- #730 tool.PanView[--]
       |--- #731 tool.lt.EntityTool [PAUSED][--]
       |--- #751 display.EntityRender
       |--- #752 display.EntityRender
       |--- #755 tool.lt.TileTool[--]
       |--- #760 tool.lt.TileTool [PAUSED][--]
       |--- #780 ui.ProjectSaver
       |--- #781 ui.modal.MetaProgress
       |--- #786 ui.modal.Progress
 |--- #787 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by mosdevly** [comment]
I should add that the save seems to have been successful, but it could be that the changes were saved to a backup before the crash.
