### ISSUE TITLE
Cannot read properties of null (reading 'drawTileRectToCanvas') (TypeError)

### ISSUE THREAD

**Issue by Nackley1** [deepnight/ldtk#927]
Stack:
```
LDtk version: 1.3.3-64bits
Cannot read properties of null (reading 'drawTileRectToCanvas')
TypeError
TypeError: Cannot read properties of null (reading 'drawTileRectToCanvas')
    at misc_JsTools.createTileRectPicker (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:207145:7)
    at ui_modal_panel_EditLayerDefs.updateForm (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275055:32)
    at ui_modal_panel_EditLayerDefs.select (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:274308:8)
    at HTMLLIElement.<anonymous> (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275436:13)
    at HTMLLIElement.dispatch (C:\Users\Natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at v.handle (C:\Users\Natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.TileTool [PAUSED][--]
       |--- #22 display.EntityRender
       |--- #23 display.EntityRender
       |--- #24 display.EntityRender
       |--- #25 display.EntityRender
       |--- #27 tool.lt.TileTool [PAUSED][--]
       |--- #43 ui.modal.panel.EditLayerDefs
       |--- #45 tool.lt.IntGridTool[--]
```

Log:
```
[FILE]         Watching file: C:\Users\Natha\Documents\Rogue Wizard Official\Assets\Rogue Wizard\Assets\Tilesets\Levels\WizardBackground.png
[FILE]         Watching file: C:\Users\Natha\Documents\Rogue Wizard Official\Assets\Rogue Wizard\Assets\Tilesets\Levels\TilemapWizardCity.png
[FILE]         Stopped watching: C:\Users\Natha\Documents\Rogue Wizard Official\Assets\Rogue Wizard\Assets\Tilesets\Levels\CaveBackground2.png
[FILE]         Watching file: C:\Users\Natha\Documents\Rogue Wizard Official\Assets\Rogue Wizard\Assets\Tilesets\Levels\CaveBackground2.png
[FILE]         Watching file: C:\Users\Natha\Documents\Rogue Wizard Official\Assets\Rogue Wizard\Assets\Tilesets\Levels\Foreground.png
[FILE]         Watching file: C:\Users\Natha\Documents\Rogue Wizard Official\Assets\Rogue Wizard\Assets\Tilesets\Levels\SpringGarden.png
[FILE]         Watching file: C:\Users\Natha\Documents\Rogue Wizard Official\Assets\Rogue Wizard\Assets\Characters\Overgrowth Collective\Villager 1.png
[FILE]         Watching file: C:\Users\Natha\Documents\Rogue Wizard Official\Assets\Rogue Wizard\Assets\Characters\Aiden\Aiden_noweapon.png
[RENDER]       Rendering world level data.Level#a367c3b0-66b0-11ec-9cd7-91690c910c97 "Entrance"...
[RENDER]       Rendering world level fields data.Level#a367c3b0-66b0-11ec-9cd7-91690c910c97 "Entrance"...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level data.Level#a36811d0-66b0-11ec-9cd7-4367627fb745 "Cross_roads"...
[RENDER]       Rendering world level data.Level#a36f8be0-66b0-11ec-9cd7-a9c628ac47cf "Shop"...
[RENDER]       Rendering world level data.Level#a3727210-66b0-11ec-9cd7-aba0184f5034 "Garden"...
[RENDER]       Rendering world level data.Level#a36a34b0-66b0-11ec-9cd7-09ebc042e238 "Water_supply"...
[RENDER]       Rendering world level data.Level#07caf540-66b0-11ec-a595-a55a7e13679d "Shop_entrance"...
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #43 ui.modal.panel.EditLayerDefs
[FILE]         Loading HTML template editLayerDefs
[FILE]         Loading HTML template pivotEditor
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[FILE]         Reading HTML template pivotEditor from cache
[EVENT]        LayerInstanceSelected
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'drawTileRectToCanvas') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'drawTileRectToCanvas')
    at misc_JsTools.createTileRectPicker (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:207145:7)
    at ui_modal_panel_EditLayerDefs.updateForm (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275055:32)
    at ui_modal_panel_EditLayerDefs.select (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:274308:8)
    at HTMLLIElement.<anonymous> (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275436:13)
    at HTMLLIElement.dispatch (C:\Users\Natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at v.handle (C:\Users\Natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.TileTool [PAUSED][--]
       |--- #22 display.EntityRender
       |--- #23 display.EntityRender
       |--- #24 display.EntityRender
       |--- #25 display.EntityRender
       |--- #27 tool.lt.TileTool [PAUSED][--]
       |--- #43 ui.modal.panel.EditLayerDefs
       |--- #45 tool.lt.IntGridTool[--]
 |--- #46 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Fixed in 1.3.5
