### ISSUE TITLE
Issue: Cannot Read Properties of Null (Reading 'drawTileRectToCanvas') (TypeError)

### ISSUE THREAD

**Issue by Nackley1** [deepnight/ldtk#928]
Not sure what's causing this. Occurs when clicking the ground layer INT. 

Stack:
```
LDtk version: 1.3.3-64bits
Cannot read properties of null (reading 'drawTileRectToCanvas')
TypeError
TypeError: Cannot read properties of null (reading 'drawTileRectToCanvas')
    at misc_JsTools.createTileRectPicker (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:207145:7)
    at ui_modal_panel_EditLayerDefs.updateForm (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275055:32)
    at ui_modal_panel_EditLayerDefs.select (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:274308:8)
    at new ui_modal_panel_EditLayerDefs (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:273931:7)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208986:5)
    at HTMLButtonElement.dispatch (C:\Users\Natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at v.handle (C:\Users\Natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)
```
Processes:
```
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.IntGridTool [PAUSED][--]
       |--- #15 display.EntityRender
       |--- #16 tool.lt.IntGridTool[--]
       |--- #29 ui.modal.panel.EditTilesetDefs
       |--- #33 ui.Tip
       |--- #34 ui.modal.panel.EditLayerDefs
```

Log:
```
[RENDER]       Rendering world level data.Level#a367c3b0-66b0-11ec-9cd7-91690c910c97 "A4_Transfer_A5"...
[RENDER]       Rendering world level fields data.Level#a367c3b0-66b0-11ec-9cd7-91690c910c97 "A4_Transfer_A5"...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world level data.Level#a36e7a70-66b0-11ec-9cd7-67ffb406aba0 "A4"...
[RENDER]       Rendering world level data.Level#a36a34b0-66b0-11ec-9cd7-09ebc042e238 "A5"...
[EVENT]        LayerInstanceSelected
[RENDER]       Rendered level UI
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[EVENT]        LayerInstanceEditedByTool
[EVENT]        LevelJsonCacheInvalidated
[RENDER]       Rendering world level fields data.Level#a367c3b0-66b0-11ec-9cd7-91690c910c97 "A4_Transfer_A5"...
[USERACTION]   IntGridTool: mode=Remove, in LayerInst#1 "Ground_Mid" [IntGrid]
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #19 ui.modal.panel.EditEnumDefs
[FILE]         Loading HTML template editEnumDefs
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #25 ui.modal.panel.EditEntityDefs
[USERACTION]   Closed panel #19 ui.modal.panel.EditEnumDefs
[FILE]         Loading HTML template editEntityDefs
[FILE]         Loading HTML template fieldDefsForm
[FILE]         Loading HTML template pivotEditor
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #29 ui.modal.panel.EditTilesetDefs
[USERACTION]   Closed panel #25 ui.modal.panel.EditEntityDefs
[FILE]         Loading HTML template editTilesetDefs
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[RENDER]       Rendering world bg...
[USERACTION]   Opened panel #34 ui.modal.panel.EditLayerDefs
[USERACTION]   Closed panel #29 ui.modal.panel.EditTilesetDefs
[FILE]         Loading HTML template editLayerDefs
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'drawTileRectToCanvas') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'drawTileRectToCanvas')
    at misc_JsTools.createTileRectPicker (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:207145:7)
    at ui_modal_panel_EditLayerDefs.updateForm (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275055:32)
    at ui_modal_panel_EditLayerDefs.select (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:274308:8)
    at new ui_modal_panel_EditLayerDefs (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:273931:7)
    at HTMLButtonElement.<anonymous> (file:///C:/Users/Natha/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208986:5)
    at HTMLButtonElement.dispatch (C:\Users\Natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:43064)
    at v.handle (C:\Users\Natha\AppData\Local\Programs\ldtk\resources\app.asar\assets\js\jquery.min.js:2:41048)

[GENERAL]      
#0 App
 |--- #3 page.Editor
       |--- #4 misc.FileWatcher
       |--- #5 display.WorldRender
       |--- #6 display.LevelRender
       |--- #7 display.Camera
       |--- #8 display.Rulers[--]
       |--- #9 tool.SelectionTool[--]
       |--- #10 tool.lt.DoNothing[--]
       |--- #11 WorldTool
       |--- #12 tool.PanView[--]
       |--- #13 tool.lt.IntGridTool [PAUSED][--]
       |--- #15 display.EntityRender
       |--- #16 tool.lt.IntGridTool[--]
       |--- #29 ui.modal.panel.EditTilesetDefs
       |--- #33 ui.Tip
       |--- #34 ui.modal.panel.EditLayerDefs
 |--- #35 page.CrashReport

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Duplicate #928, fixed in 1.3.5
