### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GoldenHaven** [deepnight/ldtk#999]
Stack:
```
LDtk version: 1.4.1-64bits
Cannot read properties of null (reading 'createTileHtmlImageFromRect')
TypeError
TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.onMouseMove (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210579:12)
    at page_Editor.onHeapsEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210428:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:122628:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165801:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165631:9)
```
Processes:
```
#0 App
 |--- #1 page.Home
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #16 tool.lt.EntityTool[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #20 tool.lt.EntityTool[--]
       |--- #22 tool.lt.EntityTool[--]
       |--- #24 tool.lt.EntityTool[--]
       |--- #26 tool.lt.EntityTool[--]
       |--- #28 tool.lt.EntityTool[--]
       |--- #30 tool.lt.EntityTool[--]
       |--- #32 tool.lt.EntityTool[--]
       |--- #34 tool.lt.EntityTool[--]
       |--- #36 tool.lt.EntityTool[--]
       |--- #38 tool.lt.EntityTool[--]
       |--- #40 tool.lt.EntityTool[--]
 |--- #15 page.CrashReport
 |--- #17 page.CrashReport
 |--- #19 page.CrashReport
 |--- #21 page.CrashReport
 |--- #23 page.CrashReport
 |--- #25 page.CrashReport
 |--- #27 page.CrashReport
 |--- #29 page.CrashReport
 |--- #31 page.CrashReport
 |--- #33 page.CrashReport
 |--- #35 page.CrashReport
 |--- #37 page.CrashReport
 |--- #39 page.CrashReport
#3 ui.modal.Progress
```

Log:
```
[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'createTileHtmlImageFromRect') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.onMouseMove (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210579:12)
    at page_Editor.onHeapsEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210428:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:122628:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165801:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165631:9)

[GENERAL]      
#0 App
 |--- #1 page.Home
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #16 tool.lt.EntityTool[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #20 tool.lt.EntityTool[--]
       |--- #22 tool.lt.EntityTool[--]
       |--- #24 tool.lt.EntityTool[--]
       |--- #26 tool.lt.EntityTool[--]
       |--- #28 tool.lt.EntityTool[--]
 |--- #15 page.CrashReport
 |--- #17 page.CrashReport
 |--- #19 page.CrashReport
 |--- #21 page.CrashReport
 |--- #23 page.CrashReport
 |--- #25 page.CrashReport
 |--- #27 page.CrashReport
 |--- #29 page.CrashReport
#3 ui.modal.Progress

[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'createTileHtmlImageFromRect') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.onMouseMove (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210579:12)
    at page_Editor.onHeapsEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210428:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:122628:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165801:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165631:9)

[GENERAL]      
#0 App
 |--- #1 page.Home
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #16 tool.lt.EntityTool[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #20 tool.lt.EntityTool[--]
       |--- #22 tool.lt.EntityTool[--]
       |--- #24 tool.lt.EntityTool[--]
       |--- #26 tool.lt.EntityTool[--]
       |--- #28 tool.lt.EntityTool[--]
       |--- #30 tool.lt.EntityTool[--]
 |--- #15 page.CrashReport
 |--- #17 page.CrashReport
 |--- #19 page.CrashReport
 |--- #21 page.CrashReport
 |--- #23 page.CrashReport
 |--- #25 page.CrashReport
 |--- #27 page.CrashReport
 |--- #29 page.CrashReport
 |--- #31 page.CrashReport
#3 ui.modal.Progress

[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'createTileHtmlImageFromRect') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.onMouseMove (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210579:12)
    at page_Editor.onHeapsEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210428:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:122628:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165801:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165631:9)

[GENERAL]      
#0 App
 |--- #1 page.Home
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #16 tool.lt.EntityTool[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #20 tool.lt.EntityTool[--]
       |--- #22 tool.lt.EntityTool[--]
       |--- #24 tool.lt.EntityTool[--]
       |--- #26 tool.lt.EntityTool[--]
       |--- #28 tool.lt.EntityTool[--]
       |--- #30 tool.lt.EntityTool[--]
       |--- #32 tool.lt.EntityTool[--]
 |--- #15 page.CrashReport
 |--- #17 page.CrashReport
 |--- #19 page.CrashReport
 |--- #21 page.CrashReport
 |--- #23 page.CrashReport
 |--- #25 page.CrashReport
 |--- #27 page.CrashReport
 |--- #29 page.CrashReport
 |--- #31 page.CrashReport
 |--- #33 page.CrashReport
#3 ui.modal.Progress

[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'createTileHtmlImageFromRect') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.onMouseMove (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210579:12)
    at page_Editor.onHeapsEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210428:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:122628:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165801:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165631:9)

[GENERAL]      
#0 App
 |--- #1 page.Home
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #16 tool.lt.EntityTool[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #20 tool.lt.EntityTool[--]
       |--- #22 tool.lt.EntityTool[--]
       |--- #24 tool.lt.EntityTool[--]
       |--- #26 tool.lt.EntityTool[--]
       |--- #28 tool.lt.EntityTool[--]
       |--- #30 tool.lt.EntityTool[--]
       |--- #32 tool.lt.EntityTool[--]
       |--- #34 tool.lt.EntityTool[--]
 |--- #15 page.CrashReport
 |--- #17 page.CrashReport
 |--- #19 page.CrashReport
 |--- #21 page.CrashReport
 |--- #23 page.CrashReport
 |--- #25 page.CrashReport
 |--- #27 page.CrashReport
 |--- #29 page.CrashReport
 |--- #31 page.CrashReport
 |--- #33 page.CrashReport
 |--- #35 page.CrashReport
#3 ui.modal.Progress

[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'createTileHtmlImageFromRect') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.onMouseMove (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210579:12)
    at page_Editor.onHeapsEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210428:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:122628:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165801:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165631:9)

[GENERAL]      
#0 App
 |--- #1 page.Home
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #16 tool.lt.EntityTool[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #20 tool.lt.EntityTool[--]
       |--- #22 tool.lt.EntityTool[--]
       |--- #24 tool.lt.EntityTool[--]
       |--- #26 tool.lt.EntityTool[--]
       |--- #28 tool.lt.EntityTool[--]
       |--- #30 tool.lt.EntityTool[--]
       |--- #32 tool.lt.EntityTool[--]
       |--- #34 tool.lt.EntityTool[--]
       |--- #36 tool.lt.EntityTool[--]
 |--- #15 page.CrashReport
 |--- #17 page.CrashReport
 |--- #19 page.CrashReport
 |--- #21 page.CrashReport
 |--- #23 page.CrashReport
 |--- #25 page.CrashReport
 |--- #27 page.CrashReport
 |--- #29 page.CrashReport
 |--- #31 page.CrashReport
 |--- #33 page.CrashReport
 |--- #35 page.CrashReport
 |--- #37 page.CrashReport
#3 ui.modal.Progress

[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'createTileHtmlImageFromRect') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.onMouseMove (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210579:12)
    at page_Editor.onHeapsEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210428:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:122628:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165801:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165631:9)

[GENERAL]      
#0 App
 |--- #1 page.Home
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #16 tool.lt.EntityTool[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #20 tool.lt.EntityTool[--]
       |--- #22 tool.lt.EntityTool[--]
       |--- #24 tool.lt.EntityTool[--]
       |--- #26 tool.lt.EntityTool[--]
       |--- #28 tool.lt.EntityTool[--]
       |--- #30 tool.lt.EntityTool[--]
       |--- #32 tool.lt.EntityTool[--]
       |--- #34 tool.lt.EntityTool[--]
       |--- #36 tool.lt.EntityTool[--]
       |--- #38 tool.lt.EntityTool[--]
 |--- #15 page.CrashReport
 |--- #17 page.CrashReport
 |--- #19 page.CrashReport
 |--- #21 page.CrashReport
 |--- #23 page.CrashReport
 |--- #25 page.CrashReport
 |--- #27 page.CrashReport
 |--- #29 page.CrashReport
 |--- #31 page.CrashReport
 |--- #33 page.CrashReport
 |--- #35 page.CrashReport
 |--- #37 page.CrashReport
 |--- #39 page.CrashReport
#3 ui.modal.Progress

[GENERAL]      Page started: page.CrashReport()
[FILE]         Loading page template: crashReport from C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/tpl/pages/crashReport.html
[ERROR]        Cannot read properties of null (reading 'createTileHtmlImageFromRect') (TypeError)
[ERROR]        TypeError: Cannot read properties of null (reading 'createTileHtmlImageFromRect')
    at misc_JsTools.createEntityPreview (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:203548:17)
    at ui_palette_EntityPalette.doRender (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:275269:33)
    at ui_palette_EntityPalette.render (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:256926:8)
    at tool_lt_EntityTool.initPalette (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:20698:17)
    at page_Editor.get_curTool (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:208517:6)
    at page_Editor.onMouseMove (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210579:12)
    at page_Editor.onHeapsEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:210428:9)
    at h2d_Scene.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:122628:4)
    at hxd_SceneEvents.dispatchListeners (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165801:6)
    at hxd_SceneEvents.emitEvent (file:///C:/Users/woodr/AppData/Local/Programs/ldtk/resources/app.asar/assets/js/renderer.js:165631:9)

[GENERAL]      
#0 App
 |--- #1 page.Home
 |--- #4 page.Editor
       |--- #5 misc.FileWatcher
       |--- #6 display.WorldRender
       |--- #7 display.LevelRender
       |--- #8 display.Camera
       |--- #9 display.Rulers[--]
       |--- #10 tool.SelectionTool[--]
       |--- #11 tool.lt.DoNothing[--]
       |--- #12 WorldTool
       |--- #13 tool.PanView[--]
       |--- #14 tool.lt.EntityTool[--]
       |--- #16 tool.lt.EntityTool[--]
       |--- #18 tool.lt.EntityTool[--]
       |--- #20 tool.lt.EntityTool[--]
       |--- #22 tool.lt.EntityTool[--]
       |--- #24 tool.lt.EntityTool[--]
       |--- #26 tool.lt.EntityTool[--]
       |--- #28 tool.lt.EntityTool[--]
       |--- #30 tool.lt.EntityTool[--]
       |--- #32 tool.lt.EntityTool[--]
       |--- #34 tool.lt.EntityTool[--]
       |--- #36 tool.lt.EntityTool[--]
       |--- #38 tool.lt.EntityTool[--]
       |--- #40 tool.lt.EntityTool[--]
 |--- #15 page.CrashReport
 |--- #17 page.CrashReport
 |--- #19 page.CrashReport
 |--- #21 page.CrashReport
 |--- #23 page.CrashReport
 |--- #25 page.CrashReport
 |--- #27 page.CrashReport
 |--- #29 page.CrashReport
 |--- #31 page.CrashReport
 |--- #33 page.CrashReport
 |--- #35 page.CrashReport
 |--- #37 page.CrashReport
 |--- #39 page.CrashReport
 |--- #41 page.CrashReport
#3 ui.modal.Progress

[FILE]         Cleared all file watches
```

**Comment by deepnight** [comment]
Fixed in 1.5
